# -*- coding: utf-8 -*-
"""home_credit_default_risk_03_FE2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMw3_RLqd2gRE4QbnYvU_3_YmHP49PmM
"""

# Commented out IPython magic to ensure Python compatibility.
#0-1　基本設定

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings
!pip install numpy==1.26.4 catboost==1.2.7

# %matplotlib inline
# %config Inlinebackend.figure_format='retina'
sns.set(style='whitegrid')
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',100)

from google.colab import drive
drive.mount('/content/drive')

#0-2 データ読込
train=pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/02FE/train_FE1.zstd.parquet')
test =pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/02FE/test_FE1.zstd.parquet')

instalments_payments=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/installments_payments.csv')

print(f"Memory Usage: {train.memory_usage().sum() / 1024**2:.2f} MB")
train.head()

'''
FE方針まとめ
1 返済能力(借入、収入、支出)
・融資額/収入 (AMT_CREDIT/AMT_INCOME_TOTAL)
・ローンの年間負債額/収入 (AMT_ANNUITY/AMT_INCOME_TOTAL)
・完済年数(AMT_CREDIT/AMT_ANNUITY)
・完済時の年齢(AMT_CREDIT/AMT_ANNUITY)+(-1*DAYS_BIRTH/365)
・ユニーク値別のデフォルト率(NAME_FAMILY_STATUS,NAME_HOUSING_TYPE)
　※リーク対策：Out-of-Fold＋Smoothing)

・ビン別のデフォルト率(CNT_CHILDREN,BU_AMT_CREDIT_SUM_DEBT_latest,POS_CNT_INSTALMENT_FUTURE_latest)
　※BU_AMT_CREDIT_SUM_DEBT_latestについてはマイナス値を0とした上でビン別を行う。その際に欠損は欠損として計算すること。
　欠損値が24％程度あることから他社債務残高がない場合は欠損となっていると思われる。そのため0で差別化可能と判断。
　※リーク対策：Out-of-Fold＋Smoothing)

2 人物的評価
・勤続日数/年齢(DAYS_EMPLOYED/DAYS_BIRTH)
・ビン別のデフォルト率（AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY)
　※リーク対策：Out-of-Fold＋Smoothing)
・提出書類の合計値(FLAG_DOCUMENT_2～21)
・異常値フラグ365243(DAYS_EMPLOYED)
・異常値フラグ15以上(AMT_REQ_CREDIT_BUREAU_QRT)
・デフォルト率の幾何平均(ORGANIZATION_TYPE,OCCUPATION_TYPE,NAME_INCOME_TYPE)
　職業・職種・学歴・インカムタイプ
　※0防止のため各カラムに0.001を加算して計算
　※リーク対策：Out-of-Fold＋Smoothing)

3 申告情報の整合性
・AMT_GOODS_PRICE(商品価格)-AMT_CREDIT(融資額)
・身分証更新日 - 年齢 (DAYS_ID_PUBLISH - DAYS_BIRTH)
・(異常値フラグの合計については試走時に寄与度0で削除したため見送り)
・ビン別デフォルト率
　train['DIFF_GOODS_CREDIT'] = train['AMT_GOODS_PRICE'] - train['AMT_CREDIT']
　DAYS_ID_PUBLISH
　※リーク対策：Out-of-Fold＋Smoothing)
・ユニーク値別のデフォルト率 (PREV_CODE_REJECT_REASON_latest)
　※リーク対策：Out-of-Fold＋Smoothing)
・フラグ別のデフォルト率(REG_REGION_NOT_LIVE_REGION,FLAG_EMP_PHONE,FLAG_WORK_PHONE)

4 特徴量一括追加

5　モデル試走(LGBMのみ)
　 FE1追加後のAUC0.77875と比較

6 その他
サンプル数が少ない場合もあり、過学習の可能性があるため
上記1～3とは分けて実施。
・同行者＋年齢層ビン(NAME_TYPE_SUITE＋20～60+)
・同行者＋直前1時間の照会有無(NAME_TYPE_SUITE＋0～1)
・同行者＋当日(24h内)の照会有無(NAME_TYPE_SUITE＋0～1)
・住宅形態＋人口密度別ビン(NAME_HOUSING_TYPE＋過疎～密集)
・住宅形態＋地域都市乗算値(1-9)(NAME_HOUSING_TYPE＋1～9)
・業種＋申請時間ビン(ORGANIZATION_TYPE＋0～3)
・職種＋申請時間ビン(OCCUPATION_TYPE＋0～3)

7 モデル試走(LGBMのみ)
　手順5の試走結果と比較して手順6が有効かどうかを検討
　有効でないなら削除

8 モデル試走(LGBM,CAT_K-FOLD)
9 パーケ出力
'''

#1-1　返済能力(借入、収入、支出)
# ・融資額/収入 (AMT_CREDIT/AMT_INCOME_TOTAL)
# ・ローンの年間負債額/収入 (AMT_ANNUITY/AMT_INCOME_TOTAL)
# ・完済年数(AMT_CREDIT/AMT_ANNUITY)
# ・完済時の年齢(AMT_CREDIT/AMT_ANNUITY)+(-1*DAYS_BIRTH/365)

def add_credit_income_ratio(df: pd.DataFrame) -> pd.DataFrame:
    # 融資額 / 収入
    income_safe = df['AMT_INCOME_TOTAL'].replace(0, np.nan)
    df['CREDIT_INCOME_RATIO'] = (df['AMT_CREDIT'] / income_safe).astype(np.float32)
    return df

def add_annuity_income_ratio(df: pd.DataFrame) -> pd.DataFrame:
    # ローンの年間負債額 / 収入
    income_safe = df['AMT_INCOME_TOTAL'].replace(0, np.nan)
    df['ANNUITY_INCOME_RATIO'] = (df['AMT_ANNUITY'] / income_safe).astype(np.float32)
    return df

def add_credit_annuity_ratio(df: pd.DataFrame) -> pd.DataFrame:
    # 完済年数
    annuity_safe = df['AMT_ANNUITY'].replace(0, np.nan)
    df['CREDIT_ANNUITY_RATIO'] = (df['AMT_CREDIT'] / annuity_safe).astype(np.float32)
    return df

def add_finish_age(df: pd.DataFrame) -> pd.DataFrame:
    # 完済時の年齢
    annuity_safe = df['AMT_ANNUITY'].replace(0, np.nan)
    loan_term_years = df['AMT_CREDIT'] / annuity_safe
    current_age_years = -df['DAYS_BIRTH'] / 365
    df['FINISH_AGE'] = (loan_term_years + current_age_years).astype(np.float32)
    return df

#1-2　返済能力(借入、収入、支出)
# ・ユニーク値別のデフォルト率(NAME_FAMILY_STATUS,NAME_HOUSING_TYPE)
# 　※リーク対策：Out-of-Fold＋Smoothing)

from sklearn.model_selection import KFold

def apply_target_encoding_oof(train_df, test_df, target_cols, target_col='TARGET', n_folds=5, smoothing=10):
    train_res = train_df.copy()
    test_res = test_df.copy()

    kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)
    global_mean = train_res[target_col].mean()

    for col in target_cols:
        new_col = f'{col}_TARGET_RATE'

        # OOF値を格納するNumPy配列を用意（型衝突を避けるため最初はfloat64）
        oof_values = np.zeros(len(train_res), dtype=np.float64)

        # 1. Trainデータへの適用 (OOF)
        for train_idx, val_idx in kf.split(train_res):
            df_t = train_res.iloc[train_idx]
            df_v = train_res.iloc[val_idx]

            # 統計量の計算
            agg = df_t.groupby(col)[target_col].agg(['count', 'mean'])
            counts = agg['count']
            means = agg['mean']

            # Smoothingの適用
            smooth = (means * counts + global_mean * smoothing) / (counts + smoothing)

            # バリデーションデータにマッピング
            oof_values[val_idx] = df_v[col].map(smooth).values

        # 欠損（学習データに存在しないカテゴリ）を全体平均で埋め、型をfloat32に固定
        oof_values = np.where(np.isnan(oof_values), global_mean, oof_values)
        train_res[new_col] = oof_values.astype(np.float32)

        # 2. Testデータへの適用 (全Trainデータを使用)
        agg = train_res.groupby(col)[target_col].agg(['count', 'mean'])
        smooth = (agg['mean'] * agg['count'] + global_mean * smoothing) / (agg['count'] + smoothing)

        test_values = test_res[col].map(smooth).values.astype(np.float64)
        test_values = np.where(np.isnan(test_values), global_mean, test_values)
        test_res[new_col] = test_values.astype(np.float32)

        print(f'Encoded: {new_col}')

    return train_res, test_res

#1-3　返済能力(借入、収入、支出)
# ・ビン別のデフォルト率(CNT_CHILDREN,BU_AMT_CREDIT_SUM_DEBT_latest,POS_CNT_INSTALMENT_FUTURE_latest)
# 　※BU_AMT_CREDIT_SUM_DEBT_latestについてはマイナス値を0とした上でビン別を行う。その際に欠損は欠損として計算すること。
# 　欠損値が24％程度あることから他社債務残高がない場合は欠損となっていると思われる。そのため0で差別化可能と判断。
# 　※リーク対策：Out-of-Fold＋Smoothing)

def apply_binned_target_encoding(train_df, test_df, col_bins_dict, target_col='TARGET', n_folds=5, smoothing=10):

    # 指定されたカラムをビン分割し、ターゲットエンコーディングを適用する関数
    # col_bins_dict: {カラム名: ビンの設定(リストまたは整数)}

    train_res = train_df.copy()
    test_res = test_df.copy()

    kf = KFold(n_splits=n_folds, shuffle=True, random_state=42)
    global_mean = train_res[target_col].mean()

    for col, bins in col_bins_dict.items():
        new_col = f'{col}_BIN_TARGET_RATE'
        temp_bin_col = f'temp_{col}_bin'

        # --- 前処理 (BU_... のマイナス値補正) ---
        t_val = train_res[col].copy()
        v_val = test_res[col].copy()

        if col == 'BU_AMT_CREDIT_SUM_DEBT_latest':
            t_val = t_val.apply(lambda x: 0 if x < 0 else x)
            v_val = v_val.apply(lambda x: 0 if x < 0 else x)

        # --- ビン分割 ---
        # 欠損値はNaNのままカテゴリとして扱われるよう、pd.cutを使用
        train_res[temp_bin_col] = pd.cut(t_val, bins=bins, include_lowest=True, labels=False)
        test_res[temp_bin_col] = pd.cut(v_val, bins=bins, include_lowest=True, labels=False)

        # OOF値を格納するNumPy配列
        oof_values = np.zeros(len(train_res), dtype=np.float64)

        # 1. Trainデータへの適用 (OOF)
        for train_idx, val_idx in kf.split(train_res):
            df_t = train_res.iloc[train_idx]
            df_v = train_res.iloc[val_idx]

            # groupbyのdropna=Falseで欠損値を1つのグループとして扱う
            agg = df_t.groupby(temp_bin_col, dropna=False)[target_col].agg(['count', 'mean'])
            counts = agg['count']
            means = agg['mean']

            smooth = (means * counts + global_mean * smoothing) / (counts + smoothing)

            # mapはNaNもキーとして扱える
            oof_values[val_idx] = df_v[temp_bin_col].map(smooth).values

        # 2. Testデータへの適用
        train_res[new_col] = oof_values.astype(np.float32)

        agg = train_res.groupby(temp_bin_col, dropna=False)[target_col].agg(['count', 'mean'])
        smooth = (agg['mean'] * agg['count'] + global_mean * smoothing) / (agg['count'] + smoothing)

        test_values = test_res[temp_bin_col].map(smooth).values.astype(np.float32)
        test_res[new_col] = test_values

        # 一時的なビンカラムを削除
        train_res = train_res.drop(columns=[temp_bin_col])
        test_res = test_res.drop(columns=[temp_bin_col])

        print(f'Encoded: {new_col}')

    return train_res, test_res

#2-1　人物的評価
# ・勤続日数/年齢(DAYS_EMPLOYED/DAYS_BIRTH)
# ・提出書類の合計値(FLAG_DOCUMENT_2～21)
# ・異常値フラグ365243(DAYS_EMPLOYED)
# ・異常値フラグ15以上(AMT_REQ_CREDIT_BUREAU_QRT)

def add_employed_birth_ratio(df: pd.DataFrame) -> pd.DataFrame:
    """勤続日数 / 年齢 (異常値365243はNaNとして処理)"""
    emp_safe = df['DAYS_EMPLOYED'].replace(365243, np.nan)
    df['EMPLOYED_BIRTH_RATIO'] = (emp_safe / df['DAYS_BIRTH']).astype(np.float32)
    return df

def add_document_count(df: pd.DataFrame) -> pd.DataFrame:
    """提出書類(FLAG_DOCUMENT_2～21)の合計値"""
    doc_cols = [f'FLAG_DOCUMENT_{i}' for i in range(2, 22)]
    available_doc_cols = [c for c in doc_cols if c in df.columns]
    df['DOCUMENT_COUNT'] = df[available_doc_cols].sum(axis=1).astype(np.float32)
    return df

def add_days_employed_anom(df: pd.DataFrame) -> pd.DataFrame:
    """DAYS_EMPLOYEDの異常値(365243)フラグ"""
    df['DAYS_EMPLOYED_ANOM'] = (df['DAYS_EMPLOYED'] == 365243).astype(np.int8)
    return df

def add_bureau_qrt_anom(df: pd.DataFrame) -> pd.DataFrame:
    """信用照会回数(QRT)が15以上の異常値フラグ"""
    # 欠損値がある場合に備え、fillna(0)してから判定
    df['AMT_REQ_CREDIT_BUREAU_QRT_ANOM'] = (df['AMT_REQ_CREDIT_BUREAU_QRT'].fillna(0) >= 15).astype(np.int8)
    return df

#2-2　人物的評価
# ・ビン別のデフォルト率（AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY)
# 　※リーク対策：Out-of-Fold＋Smoothing)
'''
#1-3 apply_binned_target_encodingを流用
'''

#2-3  人物的評価
# ・デフォルト率の幾何平均(ORGANIZATION_TYPE,OCCUPATION_TYPE,NAME_INCOME_TYPE)
# 　職業・職種・学歴・インカムタイプ
# 　※0防止のため各カラムに0.001を加算して計算
# 　※リーク対策：Out-of-Fold＋Smoothing)

def add_geometric_mean_risk(df: pd.DataFrame) -> pd.DataFrame:
    """
    業種(ORGANIZATION_TYPE)、職種(OCCUPATION_TYPE)、収入タイプ(NAME_INCOME_TYPE)
    の各デフォルト率から幾何平均を算出する。
    ※各カラムに0.001を加算して0による消失を防止
    """
    # 対象となるターゲットエンコーディング後のカラム名
    cols = [
        'ORGANIZATION_TYPE_TARGET_RATE',
        'OCCUPATION_TYPE_TARGET_RATE',
        'NAME_INCOME_TYPE_TARGET_RATE'
    ]

    # すべてのカラムが存在することを確認（FE1での削除等に備え）
    available_cols = [c for c in cols if c in df.columns]

    if len(available_cols) > 0:
        # 各値に0.001を加算して積を計算
        # 幾何平均 = (x1 * x2 * ... * xn) ^ (1/n)
        product = 1.0
        for col in available_cols:
            product *= (df[col] + 0.001)

        df['GEOM_MEAN_RISK'] = (product ** (1 / len(available_cols))).astype(np.float32)

    return df

#3-1  申告情報の整合性
# ・AMT_GOODS_PRICE(商品価格)-AMT_CREDIT(融資額)
# ・身分証更新日 - 年齢 (DAYS_ID_PUBLISH - DAYS_BIRTH)
# ・(異常値フラグの合計については試走時に寄与度0で削除したため見送り)

def add_diff_goods_credit(df: pd.DataFrame) -> pd.DataFrame:
    """
    商品価格 - 融資額 (AMT_GOODS_PRICE - AMT_CREDIT)
    頭金の額、あるいはオーバーローンの程度を示します。
    """
    df['DIFF_GOODS_CREDIT'] = (df['AMT_GOODS_PRICE'] - df['AMT_CREDIT']).astype(np.float32)
    return df

def add_days_id_publish_diff(df: pd.DataFrame) -> pd.DataFrame:
    """
    身分証更新日 - 年齢 (DAYS_ID_PUBLISH - DAYS_BIRTH)
    何歳の時に身分証を更新したかというタイミングを示します。
    """
    # どちらも負の値（現在からの遡り日数）なので、引き算で整合性が取れます
    df['DAYS_ID_PUBLISH_DIFF'] = (df['DAYS_ID_PUBLISH'] - df['DAYS_BIRTH']).astype(np.float32)
    return df

#3-2  申告情報の整合性
# ・ビン別デフォルト率
# 　train['DIFF_GOODS_CREDIT'] = train['AMT_GOODS_PRICE'] - train['AMT_CREDIT']
# 　DAYS_ID_PUBLISH
# 　※リーク対策：Out-of-Fold＋Smoothing)
'''
#1-3 apply_binned_target_encodingを流用
'''

#3-3　申告情報の整合性
# ・ユニーク値別のデフォルト率 (PREV_CODE_REJECT_REASON_latest)
# 　※リーク対策：Out-of-Fold＋Smoothing)
'''
#1-2 apply_target_encoding_oofを流用
'''

#3-4　申告情報の整合性
# ・フラグ別のデフォルト率(REG_REGION_NOT_LIVE_REGION,FLAG_EMP_PHONE,FLAG_WORK_PHONE)
'''
#1-2 apply_target_encoding_oofを流用
'''

#4-1　カラム一括追加(返済能力(借入、収入、支出))

#1-1  融資額 / 収入
train, test = add_credit_income_ratio(train), add_credit_income_ratio(test)
#1-1  ローンの年間負債額 / 収入
train, test = add_annuity_income_ratio(train), add_annuity_income_ratio(test)
#1-1  完済年数
train, test = add_credit_annuity_ratio(train), add_credit_annuity_ratio(test)
#1-1  完済時の年齢
train, test = add_finish_age(train), add_finish_age(test)
#1-2  ユニーク値別のデフォルト率(NAME_FAMILY_STATUS,NAME_HOUSING_TYPE)
target_cols = ['NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE']
train, test = apply_target_encoding_oof(train, test, target_cols)
#1-3  ビン別のデフォルト率(CNT_CHILDREN,BU_AMT_CREDIT_SUM_DEBT_latest,POS_CNT_INSTALMENT_FUTURE_latest)
col_bins_dict = {
    'CNT_CHILDREN': [-np.inf, 0, 1, 2, np.inf],
    'BU_AMT_CREDIT_SUM_DEBT_latest': 50,
    'POS_CNT_INSTALMENT_FUTURE_latest': 50
}
train, test = apply_binned_target_encoding(train, test, col_bins_dict)

#4-2　カラム一括追加(人物的評価)

# 2-1 勤続比率
train, test = add_employed_birth_ratio(train), add_employed_birth_ratio(test)
# 2-1 書類提出数
train, test = add_document_count(train), add_document_count(test)
# 2-1 就業異常フラグ
train, test = add_days_employed_anom(train), add_days_employed_anom(test)
# 2-1 照会頻度異常フラグ
train, test = add_bureau_qrt_anom(train), add_bureau_qrt_anom(test)
# 2-2　ビン別のデフォルト率（AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY)
col_bins_dict_req = {
    'AMT_REQ_CREDIT_BUREAU_HOUR': 3,
    'AMT_REQ_CREDIT_BUREAU_DAY': 3
}
train, test = apply_binned_target_encoding(train, test, col_bins_dict_req)
#2-3  デフォルト率の幾何平均(ORGANIZATION_TYPE,OCCUPATION_TYPE,NAME_INCOME_TYPE)
target_cols_geom = ['ORGANIZATION_TYPE', 'OCCUPATION_TYPE', 'NAME_INCOME_TYPE']
train, test = apply_target_encoding_oof(train, test, target_cols_geom)
train, test = add_geometric_mean_risk(train), add_geometric_mean_risk(test)

#4-3　カラム一括追加(申告情報の整合性)

# 3-1 商品価格と融資額の差分
train, test = add_diff_goods_credit(train), add_diff_goods_credit(test)
# 3-1 身分証更新タイミング
train, test = add_days_id_publish_diff(train), add_days_id_publish_diff(test)
# 3-2 ビン別デフォルト率(['DIFF_GOODS_CREDIT'] =['AMT_GOODS_PRICE'] - ['AMT_CREDIT'],DAYS_ID_PUBLISH)
col_bins_dict_consistency = {
    'DIFF_GOODS_CREDIT': 30,
    'DAYS_ID_PUBLISH': 30
}
train, test = apply_binned_target_encoding(train, test, col_bins_dict_consistency)
# 3-3 ユニーク値別のデフォルト率 (PREV_CODE_REJECT_REASON_latest)
target_cols_reject = ['PREV_CODE_REJECT_REASON_latest']
train, test = apply_target_encoding_oof(train, test, target_cols_reject)
# 3-4 フラグ別のデフォルト率(REG_REGION_NOT_LIVE_REGION,FLAG_EMP_PHONE,FLAG_WORK_PHONE)
target_cols_flags = [
    'REG_REGION_NOT_LIVE_REGION',
    'FLAG_EMP_PHONE',
    'FLAG_WORK_PHONE'
]
train, test = apply_target_encoding_oof(train, test, target_cols_flags)

#5-1　モデル試走(LGBMのみ)

import lightgbm as lgb
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
import numpy as np

def train_lgbm(X, y, X_test, params=None):
    if params is None:
        params = {
            'objective': 'binary',
            'metric': 'auc',
            'verbosity': -1,
            'learning_rate': 0.05,
            'num_leaves': 31,
            'random_state': 42,
            'feature_fraction': 0.8,
            'bagging_fraction': 0.8,
            'bagging_freq': 5,
        }

    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    oof_preds = np.zeros(len(X))
    test_preds = np.zeros(len(X_test))
    models = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        dtrain = lgb.Dataset(X_train, label=y_train)
        dval = lgb.Dataset(X_val, label=y_val, reference=dtrain)

        model = lgb.train(
            params,
            dtrain,
            valid_sets=[dtrain, dval],
            num_boost_round=10000,
            callbacks=[
                lgb.early_stopping(100),
                lgb.log_evaluation(period=0)
            ]
        )

        models.append(model)
        oof_preds[val_idx] = model.predict(X_val)
        test_preds += model.predict(X_test) / kf.n_splits

        fold_auc = roc_auc_score(y_val, oof_preds[val_idx])
        print(f"LGBM Fold {fold+1} AUC: {fold_auc:.5f}")

    overall_auc = roc_auc_score(y, oof_preds)
    print(f"LGBM Overall CV: {overall_auc:.5f}")

    return oof_preds, test_preds, models

#5-2 モデル試走(LGBMのみ)

X = train.drop(columns=['TARGET', 'SK_ID_CURR']).select_dtypes(include='number')
y = train['TARGET']
X_test = test.drop(columns=['SK_ID_CURR']).select_dtypes(include='number')
X_test = X_test[X.columns]

# モデルの実行
oof_lgb_base, pred_lgb_base, models_lgb_base = train_lgbm(X, y, X_test)

# 5-3 モデル寄与度の集計と表示 (LGBM)

# 1. 寄与度の集計と正規化 (%)
def get_lgbm_pct_importance(models, feature_names):
    # Gain（ゲイン：寄与度）を各Foldから抽出して平均
    imp = np.mean([m.feature_importance(importance_type='gain') for m in models], axis=0)

    # 合計を100%に正規化
    imp_pct = (imp / np.sum(imp)) * 100
    return pd.DataFrame({'feature': feature_names, 'Importance(%)': imp_pct})

# 寄与度データ作成
importance_df = get_lgbm_pct_importance(models_lgb_base, X.columns)

# 2. AUCスコアの取得
lgb_auc = roc_auc_score(y, oof_lgb_base)

# 3. 結果表示
print(f"■ 精度確認 (AUC) :")
print(f"  - LightGBM: {lgb_auc:.5f}\n")

# TOP 15 を抽出
top_features = importance_df.sort_values(by='Importance(%)', ascending=False).head(15).reset_index(drop=True)

print(f"■ モデルインポータンス TOP 15 (全 {len(X.columns)} 特徴量中)")
print(top_features.to_markdown(index=False))

#5-4　追加カラムの寄与度(#1～#3)

def show_fe2_exact_ranking(models_lgb, feature_names):
    # 1. 寄与度の集計
    lgb_imp = np.mean([m.feature_importance(importance_type='gain') for m in models_lgb], axis=0)
    lgb_pct = (lgb_imp / np.sum(lgb_imp)) * 100

    df = pd.DataFrame({'feature': feature_names, 'LGBM_pct': lgb_pct})
    df['Overall_Rank'] = df['LGBM_pct'].rank(ascending=False).astype(int)

    # 2. 手順1-1～3-4、および直近で作成した全追加カラム名のリスト
    # 作成した変数を網羅的に指定
    added_columns_list = [
        # 1-1 返済能力
        'CREDIT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO', 'CREDIT_ANNUITY_RATIO', 'FINISH_AGE',
        # 1-2 & 1-3 & 2-2 & 3-2 & 3-3 & 3-4 ターゲットエンコーディング / ビン系
        'NAME_FAMILY_STATUS_TARGET_RATE', 'NAME_HOUSING_TYPE_TARGET_RATE',
        'CNT_CHILDREN_BIN_TARGET_RATE', 'BU_AMT_CREDIT_SUM_DEBT_latest_BIN_TARGET_RATE',
        'POS_CNT_INSTALMENT_FUTURE_latest_BIN_TARGET_RATE',
        'AMT_REQ_CREDIT_BUREAU_HOUR_BIN_TARGET_RATE', 'AMT_REQ_CREDIT_BUREAU_DAY_BIN_TARGET_RATE',
        'ORGANIZATION_TYPE_TARGET_RATE', 'OCCUPATION_TYPE_TARGET_RATE', 'NAME_INCOME_TYPE_TARGET_RATE',
        'DIFF_GOODS_CREDIT_BIN_TARGET_RATE', 'DAYS_ID_PUBLISH_BIN_TARGET_RATE',
        'PREV_CODE_REJECT_REASON_latest_TARGET_RATE',
        'REG_REGION_NOT_LIVE_REGION_TARGET_RATE', 'FLAG_EMP_PHONE_TARGET_RATE', 'FLAG_WORK_PHONE_TARGET_RATE',
        # 2-1 人物的評価
        'EMPLOYED_BIRTH_RATIO', 'DOCUMENT_COUNT', 'DAYS_EMPLOYED_ANOM', 'BUREAU_QRT_ANOM',
        # 2-3 幾何平均
        'GEOM_MEAN_RISK',
        # 3-1 整合性
        'DIFF_GOODS_CREDIT', 'DAYS_ID_PUBLISH_DIFF',
        # 3-6～3-8 掛け合わせカテゴリ(COMBI)
        'SUITE_AGE_COMBI', 'SUITE_HOUR_COMBI', 'SUITE_DAY_COMBI',
        'HOUSING_POP_COMBI', 'HOUSING_CITY_COMBI', 'ORG_HOUR_COMBI', 'OCC_HOUR_COMBI'
    ]

    # リストに含まれるものだけを抽出（完全一致）
    added_df = df[df['feature'].isin(added_columns_list)].copy()

    # 寄与度順にソート
    added_df = added_df.sort_values(by='Overall_Rank')

    print(f"=== FE2 追加カラム (全 {len(feature_names)} 列中) ===")

    result = added_df[['feature', 'LGBM_pct', 'Overall_Rank']].reset_index(drop=True)

    if len(result) == 0:
        print("※ 指定したカラム名が見つかりませんでした。カラム名が正しいか確認してください。")
    else:
        print(result.to_markdown(index=False))

    # サマリー
    top_50 = len(result[result['Overall_Rank'] <= 50])
    top_100 = len(result[result['Overall_Rank'] <= 100])
    print(f"\n[Summary]")
    print(f"対象カラム総数: {len(result)} 個")
    print(f"全体 TOP 50 入り: {top_50} 個")
    print(f"全体 TOP 100 入り: {top_100} 個")

# 実行
show_fe2_exact_ranking(models_lgb_base, X.columns)

"""ベースライン：AUC0.77854  
FE1追加後　 ：AUC0.77875(ベースラインから+0.00021)  
FE2途中経過 ：AUC0.78450(FE1追加後から+0.00575)  

【寄与度1%以上の追加カラム】  
CREDIT_ANNUITY_RATIO(完済年数)  
GEOM_MEAN_RISK (職業・職種・学歴・インカムタイプのデフォルト率の幾何平均)  
DIFF_GOODS_CREDIT(商品価格-借入額)  

LGBMではFE1追加時と比較して、大きく改善された。  
完済年数の寄与度が高い点は自然ではあるが、借入額と年収比よりも上位に来てる部分は意外であった。時間的経過のリスクは金銭面だけでなく、健康や本人の性向の変化など、様々なリスクを孕んでいるといると思われる。
"""

#6-1　その他(同行者系)
# ・同行者＋年齢層ビン(NAME_TYPE_SUITE＋20～60+)
# ・同行者＋直前1時間の照会有無(NAME_TYPE_SUITE＋0～1)
# ・同行者＋当日(24h内)の照会有無(NAME_TYPE_SUITE＋0～1)
def add_suite_age_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """同行者 × 年齢層ビンの単純結合"""
    # .astype(str) を入れることで、category型の制約を解除して 'Unknown' を入れられるようにする
    suite = df['NAME_TYPE_SUITE'].astype(str).fillna('Unknown')

    age = df['DAYS_BIRTH'] / -365
    age_bin = pd.cut(age, bins=[0, 25, 35, 45, 55, 100],
                     labels=['20', '30', '40', '50', '60']).astype(str)

    # 結合
    df['SUITE_AGE_COMBI'] = suite + "_" + age_bin

    # 改めて category 型にする
    df['SUITE_AGE_COMBI'] = df['SUITE_AGE_COMBI'].astype('category')
    return df

def add_suite_hour_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """同行者 × 直前1時間の照会有無"""
    suite = df['NAME_TYPE_SUITE'].astype(str).fillna('Unknown')
    hour_flag = (df['AMT_REQ_CREDIT_BUREAU_HOUR'].fillna(0) > 0).astype(int).astype(str)

    df['SUITE_HOUR_COMBI'] = suite + "_" + hour_flag
    df['SUITE_HOUR_COMBI'] = df['SUITE_HOUR_COMBI'].astype('category')
    return df

def add_suite_day_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """同行者 × 当日(24h)の照会有無（エラー修正版）"""
    suite = df['NAME_TYPE_SUITE'].astype(str).fillna('Unknown')
    day_flag = (df['AMT_REQ_CREDIT_BUREAU_DAY'].fillna(0) > 0).astype(int).astype(str)

    df['SUITE_DAY_COMBI'] = suite + "_" + day_flag
    df['SUITE_DAY_COMBI'] = df['SUITE_DAY_COMBI'].astype('category')
    return df

#6-2　その他(住宅形態系)
# ・住宅形態＋人口密度別ビン(NAME_HOUSING_TYPE＋過疎～密集)
# ・住宅形態＋地域都市乗算値(1-9)(NAME_HOUSING_TYPE＋1～9)
def add_housing_pop_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """住宅形態 × 人口密度別ビン"""
    pop_bin = pd.qcut(df['REGION_POPULATION_RELATIVE'], q=4, labels=['Scanty', 'Normal', 'Dense', 'Cramped'])

    # astype(str) を挟んで category 型の制約を外す
    housing = df['NAME_HOUSING_TYPE'].astype(str).fillna('Unknown')

    df['HOUSING_POP_COMBI'] = housing + "_" + pop_bin.astype(str)
    df['HOUSING_POP_COMBI'] = df['HOUSING_POP_COMBI'].astype('category')
    return df

def add_housing_city_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """住宅形態 × 地域都市乗算値"""
    city_score = df['REGION_RATING_CLIENT'] * df['REGION_RATING_CLIENT_W_CITY']

    housing = df['NAME_HOUSING_TYPE'].astype(str).fillna('Unknown')

    df['HOUSING_CITY_COMBI'] = housing + "_" + city_score.astype(str)
    df['HOUSING_CITY_COMBI'] = df['HOUSING_CITY_COMBI'].astype('category')
    return df

#6-3　その他(申請時間系)
# ・業種＋申請時間ビン(ORGANIZATION_TYPE＋0～3)
# ・職種＋申請時間ビン(OCCUPATION_TYPE＋0～3)
# --- 共通の補助処理（時間帯のビン化） ---

def _prep_hour_bin(df: pd.DataFrame) -> pd.Series:
    """HOUR_APPR_PROCESS_START を 0, 1, 2, 3 の4つのビンに分割する補助関数"""
    # 24時間を6時間ごとに区切り、0, 1, 2, 3 というラベルを付ける
    return pd.cut(
        df['HOUR_APPR_PROCESS_START'],
        bins=[0, 6, 12, 18, 24],
        labels=['0', '1', '2', '3'],
        include_lowest=True
    ).astype(str)

def add_org_hour_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """業種 × 申請時間ビン"""
    hour_bin = _prep_hour_bin(df)
    # ORGANIZATION_TYPE も category 型の可能性があるため astype(str) を追加
    org = df['ORGANIZATION_TYPE'].astype(str).fillna('Unknown')

    df['ORG_HOUR_COMBI'] = org + "_" + hour_bin
    df['ORG_HOUR_COMBI'] = df['ORG_HOUR_COMBI'].astype('category')
    return df

def add_occ_hour_interaction(df: pd.DataFrame) -> pd.DataFrame:
    """職種 × 申請時間ビン"""
    hour_bin = _prep_hour_bin(df)
    # OCCUPATION_TYPE も category 型の可能性があるため astype(str) を追加
    occ = df['OCCUPATION_TYPE'].astype(str).fillna('Unknown')

    df['OCC_HOUR_COMBI'] = occ + "_" + hour_bin
    df['OCC_HOUR_COMBI'] = df['OCC_HOUR_COMBI'].astype('category')
    return df

#6-4　その他　カラム一括追加

# 6-1 同行者 × 年齢層
train, test = add_suite_age_interaction(train), add_suite_age_interaction(test)
# 6-1 同行者 × 1時間以内照会
train, test = add_suite_hour_interaction(train), add_suite_hour_interaction(test)
# 6-1 同行者 × 当日照会
train, test = add_suite_day_interaction(train), add_suite_day_interaction(test)
# 6-2 住宅形態 × 人口密度
train, test = add_housing_pop_interaction(train), add_housing_pop_interaction(test)
# 6-2 住宅形態 × 都市スコア
train, test = add_housing_city_interaction(train), add_housing_city_interaction(test)
# 6-3 業種 × 申請時間ビンの作成
train = add_org_hour_interaction(train)
test = add_org_hour_interaction(test)
# 6-4 職種 × 申請時間ビンの作成
train = add_occ_hour_interaction(train)
test = add_occ_hour_interaction(test)

#7-1  モデル試走(LGBMのみ)

# 除外リストの作成
potential_drop_cols = ['TARGET', 'SK_ID_CURR', 'index']
drop_cols = [c for c in potential_drop_cols if c in train.columns]

# 特徴量 (数値型 + カテゴリ型) の抽出
X = train.drop(columns=drop_cols).select_dtypes(include=['number', 'category'])
y = train['TARGET']

# テストデータも同様に揃える
test_drop = [c for c in ['SK_ID_CURR', 'index'] if c in test.columns]
X_test = test.drop(columns=test_drop).select_dtypes(include=['number', 'category'])
X_test = X_test.reindex(columns=X.columns)

oof_lgb_base, pred_lgb_base, models_lgb_base = train_lgbm(X, y, X_test)

#7-2  モデル寄与度

# 1. 寄与度の集計と正規化 (%)
def get_lgbm_pct_importance(models, feature_names):
    # Gain（ゲイン：寄与度）を各Foldから抽出して平均
    imp = np.mean([m.feature_importance(importance_type='gain') for m in models], axis=0)

    # 合計を100%に正規化
    imp_pct = (imp / np.sum(imp)) * 100
    return pd.DataFrame({'feature': feature_names, 'Importance(%)': imp_pct})

# 寄与度データ作成
importance_df = get_lgbm_pct_importance(models_lgb_base, X.columns)

# 2. AUCスコアの取得
lgb_auc = roc_auc_score(y, oof_lgb_base)

# 3. 結果表示
print(f"■ 精度確認 (AUC) :")
print(f"  - LightGBM: {lgb_auc:.5f}\n")

# TOP 15 を抽出
top_features = importance_df.sort_values(by='Importance(%)', ascending=False).head(15).reset_index(drop=True)

print(f"■ モデルインポータンス TOP 15 (全 {len(X.columns)} 特徴量中)")
print(top_features.to_markdown(index=False))

#7-3  モデル寄与度(追加カラム)

def show_fe2_exact_ranking(models_lgb, feature_names):
    # 1. 寄与度の集計
    lgb_imp = np.mean([m.feature_importance(importance_type='gain') for m in models_lgb], axis=0)
    lgb_pct = (lgb_imp / np.sum(lgb_imp)) * 100

    df = pd.DataFrame({'feature': feature_names, 'LGBM_pct': lgb_pct})
    df['Overall_Rank'] = df['LGBM_pct'].rank(ascending=False).astype(int)

    # 2. 手順1-1～3-4、および直近で作成した全追加カラム名のリスト
    # 作成した変数を網羅的に指定
    added_columns_list = [
    # 6-1～6-4 掛け合わせカテゴリ(COMBI)
    'SUITE_AGE_COMBI', 'SUITE_HOUR_COMBI', 'SUITE_DAY_COMBI',
    'HOUSING_POP_COMBI', 'HOUSING_CITY_COMBI', 'ORG_HOUR_COMBI', 'OCC_HOUR_COMBI'
]

    # リストに含まれるものだけを抽出（完全一致）
    added_df = df[df['feature'].isin(added_columns_list)].copy()

    # 寄与度順にソート
    added_df = added_df.sort_values(by='Overall_Rank')

    print("=== FE2 追加カラム  ===")

    result = added_df[['feature', 'LGBM_pct', 'Overall_Rank']].reset_index(drop=True)

    if len(result) == 0:
        print("※ 指定したカラム名が見つかりませんでした。カラム名が正しいか確認してください。")
    else:
        print(result.to_markdown(index=False))

    # サマリー
    top_50 = len(result[result['Overall_Rank'] <= 50])
    top_100 = len(result[result['Overall_Rank'] <= 100])
    print(f"\n[Summary]")
    print(f"対象カラム総数: {len(result)} 個")
    print(f"全体 TOP 50 入り: {top_50} 個")
    print(f"全体 TOP 100 入り: {top_100} 個")

# 実行
show_fe2_exact_ranking(models_lgb_base, X.columns)

"""精度低下、過学習やノイズとなっていると思われる。"""

#7-3  モデル寄与度　ユニーク値確認
# 確認したいカテゴリ変数リスト
combi_cols = [
    'ORG_HOUR_COMBI',
    'OCC_HOUR_COMBI',
    'SUITE_AGE_COMBI',
    'HOUSING_CITY_COMBI',
    'HOUSING_POP_COMBI',
    # 'SUITE_DAY_COMBI',　寄与度が低いためコメントアウト
    # 'SUITE_HOUR_COMBI'
]

def check_combi_unique(df, cols):
    results = []
    for col in cols:
        if col in df.columns:
            results.append({
                'feature': col,
                'n_unique': df[col].nunique(),
                'missing': df[col].isnull().sum(),
                'most_frequent': df[col].value_counts().index[0],
                'min_freq': df[col].value_counts().values[-1] # 最も出現回数が少ないカテゴリの数
            })
    return pd.DataFrame(results)

# 実行
unique_summary = check_combi_unique(train, combi_cols)
print("=== COMBI系カラムのユニーク値・頻度確認 ===")
print(unique_summary.to_markdown(index=False))

""" HOUSING_CITY_COMBI以外はユニーク値に対して少数のサンプルしかいない値があるため、過学習に陥っている可能性が高い。特にORG_HOUR_COMBIはその傾向が強い。  
またSUITE_DAY_COMBIとSUITE_HOUR_COMBIはノイズとなっていると思われる。  
他の4カラムについてはサンプル数100以下をまとめて再度実行を行う。
"""

#7-3  モデル寄与度　再試走

# def tidy_up_combi(df, col, threshold=100):
#     """出現頻度が threshold 未満のカテゴリを 'Other' にまとめる"""
#     # 頻度を計算
#     counts = df[col].value_counts()
#     # しきい値未満のカテゴリ名を抽出
#     rare_labels = counts[counts < threshold].index

#     # 置換処理
#     df[col] = df[col].astype(str).replace(rare_labels, 'Other').astype('category')

#     # 確認用プリント
#     print(f"{col}: {len(rare_labels)} 個のレアカテゴリを 'Other' に統合しました。")
#     return df

# # 1. カテゴリの集約を実行
# target_cols = ['ORG_HOUR_COMBI', 'OCC_HOUR_COMBI', 'SUITE_AGE_COMBI', 'HOUSING_CITY_COMBI']

# for col in target_cols:
#     train = tidy_up_combi(train, col, threshold=100)
#     test = tidy_up_combi(test, col, threshold=100)

# # 2. 学習用データの再作成
# potential_drop_cols = ['TARGET', 'SK_ID_CURR', 'index']
# drop_cols = [c for c in potential_drop_cols if c in train.columns]

# X = train.drop(columns=drop_cols).select_dtypes(include=['number', 'category'])
# y = train['TARGET']
# X_test = test.drop(columns=[c for c in ['SK_ID_CURR', 'index'] if c in test.columns]).reindex(columns=X.columns)

# # 3. 再学習
# oof_lgb_base, pred_lgb_base, models_lgb_base = train_lgbm(X, y, X_test)

"""LGBM Overall CV: 0.78289

サンプルが少ないユニーク値を統合するも精度の低下は変わらないため、過学習になりにくいHOUSING_POP_COMBI のみ残して他は削除
"""

#7-4　不要カラム削除

# 採用しないカラムのリスト
cols_to_drop = [
    'ORG_HOUR_COMBI',
    'OCC_HOUR_COMBI',
    'SUITE_AGE_COMBI',
    'HOUSING_CITY_COMBI',
    'SUITE_DAY_COMBI',
    'SUITE_HOUR_COMBI'
]

train = train.drop(columns=[c for c in cols_to_drop if c in train.columns])
test = test.drop(columns=[c for c in cols_to_drop if c in test.columns])

import gc
gc.collect()

#8-1　モデル試走　CAT関数

!pip install catboost==1.2.7 --break-system-packages

def train_catboost(X, y, X_test, params=None):
    if params is None:
        params = {
            'loss_function': 'Logloss',
            'eval_metric': 'AUC',
            'learning_rate': 0.05,
            'iterations': 10000,
            'random_seed': 42,
            'verbose': 0,
            'early_stopping_rounds': 100,
            'task_type': 'GPU'
        }

    cat_features = X.select_dtypes(include=['category', 'object']).columns.tolist()

    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    oof_preds = np.zeros(len(X))
    test_preds = np.zeros(len(X_test))
    models = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(X, y)):
        X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
        y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = CatBoostClassifier(**params)

        model.fit(
            X_train, y_train,
            eval_set=(X_val, y_val),
            use_best_model=True,
            cat_features=cat_features
        )

        models.append(model)
        oof_preds[val_idx] = model.predict_proba(X_val)[:, 1]
        test_preds += model.predict_proba(X_test)[:, 1] / kf.n_splits
        print(f"CatBoost Fold {fold+1} AUC: {roc_auc_score(y_val, oof_preds[val_idx]):.5f}")

    print(f"CatBoost Overall CV: {roc_auc_score(y, oof_preds):.5f}")
    return oof_preds, test_preds, models

#8-2  メモリ開放
import gc

# 以前の実行で残っている可能性がある大きな変数を削除
# もし変数名が違っていてもエラーにならないよう locals() でチェック
for var_name in ['X', 'X_test', 'oof_lgb', 'oof_cat', 'models_lgb', 'models_cat']:
    if var_name in locals():
        del locals()[var_name]

gc.collect()

#8-3　モデル試走(LGBM)

from catboost import CatBoostClassifier

# --- 特徴量の再抽出 ---
potential_drop_cols = ['TARGET', 'SK_ID_CURR', 'index']
drop_cols = [c for c in potential_drop_cols if c in train.columns]

# X, y の作成
X = train.drop(columns=drop_cols).select_dtypes(include=['number', 'category'])
y = train['TARGET']

# X_test の作成
test_drop = [c for c in ['SK_ID_CURR', 'index'] if c in test.columns]
X_test = test.drop(columns=test_drop).select_dtypes(include=['number', 'category'])
X_test = X_test.reindex(columns=X.columns)

# --- モデル訓練（変数名を X, y, X_test に合わせる） ---
print("--- Starting LightGBM ---")
oof_lgb, test_lgb, models_lgb = train_lgbm(X, y, X_test)

"""LGBM   
ベースライン　　　　　　　　　 ：AUC0.77854  
FE1(#1～#３)追加後　　　　　　 ：AUC0.77875(ベースラインから+0.00021)  
FE2途中経過　　　　　　　　　　：AUC0.78450(FE1追加後から+0.00575)  
FE2(HOUSING_POP_COMBI)追加後：AUC0.78711(途中経過から+0.00261)  
"""

#8-4　モデル試走(CAT)

# --- CatBoost用の前処理 ---
# カテゴリ型の列を特定
cat_cols = X.select_dtypes(include=['category', 'object']).columns

# カテゴリ列の欠損値を 'Unknown' という文字列で埋め、さらに型を強制的に文字列(str)にする
for col in cat_cols:
    X[col] = X[col].astype(str).replace('nan', 'Unknown')
    X_test[col] = X_test[col].astype(str).replace('nan', 'Unknown')

print("--- Starting CatBoost ---")
oof_cat, test_cat, models_cat = train_catboost(X, y, X_test)

"""CatBoost Overall CV: 0.78959"""

#8-5　モデル寄与度(LGBM,CAT)
from sklearn.metrics import roc_auc_score

# --- 1. 寄与度の集計と正規化 (%) ---
def get_pct_importance(models, model_name, feature_names):
    if model_name == 'LGBM':
        # Importance Type 'gain' で集計（より精度に直結する指標）
        imp = np.mean([m.feature_importance(importance_type='gain') for m in models], axis=0)
    else:
        # CatBoostのImportanceを平均
        imp = np.mean([m.get_feature_importance() for m in models], axis=0)

    imp_pct = (imp / np.sum(imp)) * 100
    return pd.DataFrame({'feature': feature_names, f'{model_name}_pct': imp_pct})

# 学習で使った名前に合わせてデータ作成
lgb_imp_df = get_pct_importance(models_lgb, 'LGBM', X.columns)
cat_imp_df = get_pct_importance(models_cat, 'CAT', X.columns)

# --- 2. マージして比較表を作成 ---
comparison_df = pd.merge(lgb_imp_df, cat_imp_df, on='feature')

# AUCスコアの取得（学習済み変数 oof_lgb, oof_cat を使用）
lgb_auc = roc_auc_score(y, oof_lgb)
cat_auc = roc_auc_score(y, oof_cat)

# アンサンブル
ensemble_oof = (oof_lgb + oof_cat) / 2
ens_auc = roc_auc_score(y, ensemble_oof)

# --- 3. 結果表示 ---
print(f"--- 精度比較 (AUC) ---")
print(f"LightGBM: {lgb_auc:.5f}")
print(f"CatBoost: {cat_auc:.5f}")
print(f"Ensemble: {ens_auc:.5f}")
print("-" * 30)

# TOP15の抽出
lgb_top15 = comparison_df.sort_values(by='LGBM_pct', ascending=False).head(15)[['feature', 'LGBM_pct']]
cat_top15 = comparison_df.sort_values(by='CAT_pct', ascending=False).head(15)[['feature', 'CAT_pct']]

# 横並び表示用の整形
side_by_side = pd.concat([
    lgb_top15.reset_index(drop=True).rename(columns={'feature': 'LGBM Feature', 'LGBM_pct': 'LGBM(%)'}),
    cat_top15.reset_index(drop=True).rename(columns={'feature': 'CatBoost Feature', 'CAT_pct': 'CAT(%)'})
], axis=1)

print(f"\nモデル別インポータンス TOP 15")
print(side_by_side.to_markdown(index=False))

# 共通項目の抽出
common_top = set(lgb_top15['feature']) & set(cat_top15['feature'])
print(f"\n両モデル共通のTOP15項目: {len(common_top)}件")
print(sorted(list(common_top)))

"""CatBoost クリーニング後: 0.7820  
CatBoost FE後　　　　　: 0.78959  
※クリーニング時はホールドアウト方式
"""

#8-6　追加カラムの寄与度

def show_fe2_exact_ranking_combined(models_lgb, models_cat, feature_names):
    # --- 1. LGBMの寄与度集計 ---
    lgb_imp = np.mean([m.feature_importance(importance_type='gain') for m in models_lgb], axis=0)
    lgb_pct = (lgb_imp / np.sum(lgb_imp)) * 100
    df_lgb = pd.DataFrame({'feature': feature_names, 'LGBM_pct': lgb_pct})
    df_lgb['LGBM_Rank'] = df_lgb['LGBM_pct'].rank(ascending=False).astype(int)

    # --- 2. CatBoostの寄与度集計 ---
    cat_imp = np.mean([m.get_feature_importance() for m in models_cat], axis=0)
    cat_pct = (cat_imp / np.sum(cat_imp)) * 100
    df_cat = pd.DataFrame({'feature': feature_names, 'CAT_pct': cat_pct})
    df_cat['CAT_Rank'] = df_cat['CAT_pct'].rank(ascending=False).astype(int)

    # --- 3. マージと抽出 ---
    df_combined = pd.merge(df_lgb, df_cat, on='feature')

    added_columns_list = [
        'CREDIT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO', 'CREDIT_ANNUITY_RATIO', 'FINISH_AGE',
        'NAME_FAMILY_STATUS_TARGET_RATE', 'NAME_HOUSING_TYPE_TARGET_RATE',
        'CNT_CHILDREN_BIN_TARGET_RATE', 'BU_AMT_CREDIT_SUM_DEBT_latest_BIN_TARGET_RATE',
        'POS_CNT_INSTALMENT_FUTURE_latest_BIN_TARGET_RATE',
        'AMT_REQ_CREDIT_BUREAU_HOUR_BIN_TARGET_RATE', 'AMT_REQ_CREDIT_BUREAU_DAY_BIN_TARGET_RATE',
        'ORGANIZATION_TYPE_TARGET_RATE', 'OCCUPATION_TYPE_TARGET_RATE', 'NAME_INCOME_TYPE_TARGET_RATE',
        'DIFF_GOODS_CREDIT_BIN_TARGET_RATE', 'DAYS_ID_PUBLISH_BIN_TARGET_RATE',
        'PREV_CODE_REJECT_REASON_latest_TARGET_RATE',
        'REG_REGION_NOT_LIVE_REGION_TARGET_RATE', 'FLAG_EMP_PHONE_TARGET_RATE', 'FLAG_WORK_PHONE_TARGET_RATE',
        'EMPLOYED_BIRTH_RATIO', 'DOCUMENT_COUNT', 'DAYS_EMPLOYED_ANOM', 'BUREAU_QRT_ANOM',
        'GEOM_MEAN_RISK', 'DIFF_GOODS_CREDIT', 'DAYS_ID_PUBLISH_DIFF', 'HOUSING_POP_COMBI'
    ]

    available_added_cols = [c for c in added_columns_list if c in feature_names]
    result = df_combined[df_combined['feature'].isin(available_added_cols)].copy()

    # LGBMの順位を基準にソート（C変更時はCAT_Rank）
    result = result.sort_values(by='LGBM_Rank').reset_index(drop=True)

    # 表示用にカラムを並べ替え
    display_cols = ['feature', 'LGBM_pct', 'LGBM_Rank', 'CAT_pct', 'CAT_Rank']

    print(f"=== FE2 追加カラム評価 (LGBM & CatBoost 合同) ===")
    if len(result) == 0:
        print("※ 指定したカラムが見つかりませんでした。")
    else:
        print(result[display_cols].to_markdown(index=False))

    # --- サマリー ---
    print(f"\n[Summary]")
    print(f"評価対象数: {len(result)} 個")
    print(f"LGBM TOP 100入り: {len(result[result['LGBM_Rank'] <= 100])} 個")
    print(f"CAT  TOP 100入り: {len(result[result['CAT_Rank'] <= 100])} 個")

# --- 実行 ---
show_fe2_exact_ranking_combined(models_lgb, models_cat, X.columns)

#8-7　共通の寄与度0カラムの削除

# --- 1. 各モデルの寄与度を取得 ---
lgb_imp = np.mean([m.feature_importance(importance_type='gain') for m in models_lgb], axis=0)
cat_imp = np.mean([m.get_feature_importance() for m in models_cat], axis=0)

# --- 2. 寄与度が0のカラムを特定 ---
lgb_zero_cols = set(X.columns[lgb_imp == 0])
cat_zero_cols = set(X.columns[cat_imp == 0])

# 両方のモデルで寄与度が0のカラム（共通部分）
common_zero_cols = sorted(list(lgb_zero_cols & cat_zero_cols))

# --- 3. 全カラムを表示 ---
print(f"=== 共通の寄与度0カラム一覧 (全 {len(common_zero_cols)} 件) ===")
if len(common_zero_cols) > 0:
    import pprint
    # 縦に並べて見やすく表示
    pprint.pprint(common_zero_cols)

    # train / test / X / X_test から削除
    # inplace=Trueを使わず、確実に再代入
    X = X.drop(columns=common_zero_cols)
    X_test = X_test.drop(columns=common_zero_cols)

    # 元のデータフレームも更新（列が存在する場合のみ）
    train = train.drop(columns=[c for c in common_zero_cols if c in train.columns])
    test = test.drop(columns=[c for c in common_zero_cols if c in test.columns])

    print(f"削除後の特徴量数: {X.shape[1]}")
else:
    print("削除対象のカラムなし")

#9-1 パーケ出力

import os

# --- 1. ファイル名の設定（FE2に変更） ---
train_filename = 'train_FE2.zstd.parquet'
test_filename = 'test_FE2.zstd.parquet'

# --- 2. zstd圧縮で保存 ---
train.to_parquet(train_filename, compression='zstd', index=False)
test.to_parquet(test_filename, compression='zstd', index=False)

# --- 3. 保存したファイルのサイズを確認 ---
train_size_zstd = os.path.getsize(train_filename) / 1024**2
test_size_zstd = os.path.getsize(test_filename) / 1024**2

print(f" {train_filename}")
print(f"Trainファイルサイズ (zstd): {train_size_zstd:.2f} MB")
print(f"Test ファイルサイズ (zstd): {test_size_zstd:.2f} MB")

"""FE2まとめ  
手順6で追加したその他カラムについて、目検で気になるものを追加したが細分化しすぎたことで、過学習に陥り、精度面が低下した。  
特徴量の追加は多いほどモデルの学習材料が増えて良い結果となると考えていたが寄与度の高いORG_HOUR_COMBIを削除後に精度が向上したことを考えると、重要な特徴量を追加するのと同程度にノイズとなるカラムを削除することが重要だと学んだ。  
EDA時には非線形の特徴を捉えられていたが結果として有効な特徴量ではなかったため、次回以降はサンプル数の程度を考慮して追加・検討を行っていく必要がある。  
EDAとモデリングの橋渡しにおいて、カテゴリ型を用いる場合はユニーク値別にそのパターンは何件のデータに支えられているかを検討すべきであり、特に寄与度の高いものほど細分化による過学習に注意すべきである。

次回以降の検討手段


1.   Coverage（被覆率）:  
その特徴的なパターンが、全データのうち何％に該当するかを確認する（0.1%以下のパターンに凝った名前をつけても、モデル全体には悪影響の方が大きくなる）

1.   信頼区間の確認:  
平均値の差を見るだけでなく、エラーバー（標準誤差）を表示させ、その差が統計的に偶然ではないかを確認する。
2.   Feature Selectionの自動化:  
 LGBM の feature_importances_ を取得し、下位10〜20%のほとんど使われていない列を一度に削除して再学習し、比較。  
 ※ORG_HOUR_COMBIのように寄与度が高いものはこの方法では確認できないため注意。
2.   カテゴリ変数の「まとめ直し」:  
今回過学習の原因となったカラムがあれば、threshold をサンプル数の5%未満で纏めるなど、より「太い」カテゴリにして再投入。
"""