# -*- coding: utf-8 -*-
"""home_credit_default_risk_02_EDA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yAq2yRl9mD6AsAUxUojkzLiQ3rov7_Q
"""

# Commented out IPython magic to ensure Python compatibility.
#0-1　基本設定

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings

# %matplotlib inline
# %config Inlinebackend.figure_format='retina'
sns.set(style='whitegrid')
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',100)

from google.colab import drive
drive.mount('/content/drive')

#0-2 データ読込
train=pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/01クリーニング/application_train_cleaning.zstd.parquet')
test =pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/01クリーニング/application_test_cleaning.zstd.parquet')

instalments_payments=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/installments_payments.csv')

print(f"Memory Usage: {train.memory_usage().sum() / 1024**2:.2f} MB")
train.head()

'''
EDA方針メモ
EDA1では試走結果の寄与度を起点に第1・第2有力指標について検証した。
本ノートブック（EDA2）では、返済能力・人物評価・申告情報の整合性・その他の観点から
組み合わせの検証を行う。

5 返済能力(借入、収入、支出)
6 人物的評価
7 申告情報の整合性
8 その他(目検で気になるものあれば)
'''

#5-1 返済能力(借入、収入、支出)　欠損及び基本統計量
'''
・借入関連カラム
AMT_CREDIT(融資額)、AMT_ANNUITY (ローンの年間支払い額)、AMT_GOODS_PRICE(商品価格)
・収入関連カラム
AMT_INCOME_TOTAL(顧客の収入)
・支出関連カラム
FLAG_OWN_CAR(車所有フラグ)、CNT_CHILDREN(子供の数)、NAME_FAMILY_STATUS(家族構成)
NAME_HOUSING_TYPE(住宅状況(賃貸等))、REGION_POPULATION_RELATIVE(居住地の人口密度)
CNT_FAM_MEMBERS (世帯人数)
bureau.csv　AMT_CREDIT_SUM_DEBT(信用情報機関の信用情報に記載されている現在の債務)
※BU_AMT_CREDIT_SUM_DEBT_latest
POS_CASH_balance.csv　CNT_INSTALMENT_FUTURE(前回のクレジットの残りの支払い額)
※POS_CNT_INSTALMENT_FUTURE_latest
'''

def get_stats_summary(df, cols):
    """
    指定したカラムの欠損率と基本統計量をDataFrameで返す
    """
    summary = pd.DataFrame({
        'Missing%': df[cols].isnull().mean() * 100,
        'Mean': df[cols].mean(numeric_only=True),
        'Median': df[cols].median(numeric_only=True),
        'Min': df[cols].min(numeric_only=True),
        'Max': df[cols].max(numeric_only=True)
    })
    return summary

repayment_capacity_cols1 = [
    # --- 借入関連 ---
    'AMT_CREDIT',          # 融資額
    'AMT_ANNUITY',         # ローンの年間支払い額
    'AMT_GOODS_PRICE',     # 商品価格

    # --- 収入関連 ---
    'AMT_INCOME_TOTAL',    # 顧客の収入

    # --- 支出・属性関連 ---
    'FLAG_OWN_CAR',        # 車所有フラグ
    'CNT_CHILDREN',        # 子供の数
    'NAME_FAMILY_STATUS',  # 家族構成
    'NAME_HOUSING_TYPE',   # 住宅状況
    'REGION_POPULATION_RELATIVE', # 居住地の人口密度
    'CNT_FAM_MEMBERS',     # 世帯人数

    # --- 他社債務・支払い状況（集約済み最新値） ---
    'BU_AMT_CREDIT_SUM_DEBT_latest',   # 信用情報機関の債務残高
    'POS_CNT_INSTALMENT_FUTURE_latest' # POS契約の残り支払い回数
]
repayment_capacity_summary = get_stats_summary(train, repayment_capacity_cols1)
print(repayment_capacity_summary)

"""*   AMT_CREDITとAMT_GOODS_PRICE  
最小値と最大値は一致しているものの、中央値と平均値には乖離が見られる。以降のEDA手順7の申告情報の整合性で組み合わせて検討。  

*   AMT_INCOME_TOTAL  
最大値がかなりの高額であり、#1-4で整理したとおり、FEにて異常値としてフラグ追加予定。  

*   BU_AMT_CREDIT_SUM_DEBT_latest   
最小値がマイナスであり、組み合わせ時に要注意。  
可能性としては過払い金や誤入力が考えられる。


"""

#5-2 返済能力(借入、収入、支出)　カテゴリ型の基本情報

def analyze_category_risk(df, cols, target_col='TARGET'):
    for col in cols:
        if col in df.columns:
            print(f"\n▼ カラム名: {col}")
            print("-" * 80)

            # 1. 基本集計（件数、構成比、デフォルト率）
            summary = df.groupby(col, dropna=False).agg(
                件数=(target_col, 'size'),
                デフォルト件数=(target_col, 'sum'),
                デフォルト率=(target_col, 'mean')
            )

            # 構成比(%)を追加
            summary['構成比(%)'] = (summary['件数'] / len(df)) * 100
            # デフォルト率を%表記に
            summary['デフォルト率(%)'] = summary['デフォルト率'] * 100

            # 2. 欠損率の算出（全体に対して）
            missing_pct = df[col].isnull().mean() * 100

            # 表示用に整形（ユニーク数の降順を意識しつつ、デフォルト率でソート）
            res = summary[['件数', '構成比(%)', 'デフォルト率(%)']].sort_values('デフォルト率(%)', ascending=False)

            print(res)
            print(f"\n[補足] このカラムの全体欠損率: {missing_pct:.2f}%")
            print("-" * 80)


repayment_capacity_cols1 = ['NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'FLAG_OWN_CAR']
analyze_category_risk(train, repayment_capacity_cols1)

"""*   NAME_FAMILY_STATUS
不明を除けば未亡人のデフォルト率が低く５％程度であり、独身者は想定通り高く9.81%であった。また、意外にも事実婚が独身者よりも高く9.94％となった。
*   NAME_HOUSING_TYPE
賃貸は想定通り高く、デフォルト率が12.31％でトップとなった。また、次点では意外にも親と同居している場合であり、11.7％となった。


*   FLAG_OWN_CAR
車両の所有によるデフォルト率の差は1.26％であり、あまり有意な差は見られず。

FE追加事項



1.   融資額/収入 (AMT_CREDIT/AMT_INCOME_TOTAL)  
1.   ローンの年間負債額/収入 (AMT_ANNUITY/AMT_INCOME_TOTAL)
1.   完済年数(AMT_CREDIT/AMT_ANNUITY)
1.   完済時の年齢(AMT_CREDIT/AMT_ANNUITY)+(-1*DAYS_BIRTH/365)
1.   ユニーク値別のデフォルト率(NAME_FAMILY_STATUS,NAME_HOUSING_TYPE)  
※リーク対策：Out-of-Fold＋Smoothing)  
2.   ビン別のデフォルト率(CNT_CHILDREN,BU_AMT_CREDIT_SUM_DEBT_latest,POS_CNT_INSTALMENT_FUTURE_latest)  
※BU_AMT_CREDIT_SUM_DEBT_latestについてはマイナス値を0とした上でビン別を行う。その際に欠損は欠損として計算すること。  
欠損値が24％程度あることから他社債務残高がない場合は欠損となっていると思われる。そのため0で差別化可能と判断。  
※リーク対策：Out-of-Fold＋Smoothing)   

2.   融資額/(収入-収入*上記1、2の各デフォルト率)  
支出面での補正を考慮するため追加。  
※各デフォルト率に１つでも0があると0となってしまうため、各デフォルト率に0.001を加算した状態で計算
"""

#6-1 人物的評価　欠損及び基本統計量
'''
NAME_TYPE_SUITE(ローン申請時の同行者)
NAME_INCOME_TYPE(収入タイプ（自営業者、会社員、産休中など）)
NAME_EDUCATION_TYPE(学歴)
CNT_CHILDREN(子供の数)、NAME_FAMILY_STATUS(家族構成)
DAYS_BIRTH(年齢)
DAYS_EMPLOYED(勤続年数)
REGION_RATING_CLIENT(住居の地域評価)
REGION_RATING_CLIENT_W_CITY(住居の都市評価)
REG_REGION_NOT_LIVE_REGION(連絡先住所と居住地の相異フラグ)
OCCUPATION_TYPE(職業)
ORGANIZATION_TYPE(勤務先の業種)
FLAG_DOCUMENT_2～21(提出文書2～21　※1はカラム説明になし)
AMT_REQ_CREDIT_BUREAU_HOUR(申請の1時間前に信用情報機関に対して行われた顧客に関する照会件数)
AMT_REQ_CREDIT_BUREAU_DAY(申請前日（申請前1時間を除く）に信用情報機関に対して行われた顧客に関する照会件数)
AMT_REQ_CREDIT_BUREAU_WEEK(申請前1週間（申請前日を除く）に信用情報機関に対して行われた、当該顧客に関する照会件数)
AMT_REQ_CREDIT_BUREAU_MON(申請前1ヶ月間（申請前1週間を除く）に信用情報機関に対して行われた、当該顧客に関する照会件数)
AMT_REQ_CREDIT_BUREAU_QRT(申請前3ヶ月間（申請前1ヶ月間を除く）に、信用情報機関に対して行われた顧客に関する照会件数)
AMT_REQ_CREDIT_BUREAU_YEAR(顧客に関する信用情報機関への照会件数（申請前の3ヶ月を除く、1日あたり）)
bureau.csv　CREDIT_DAY_OVERDUE(サンプルにおける関連ローン申請時点でのCBクレジットの延滞日数)
※BU_CREDIT_DAY_OVERDUE_max,BU_CREDIT_DAY_OVERDUE_latest
bureau.csv　CNT_CREDIT_PROLONG(信用情報機関の信用延長は何回行われましたか？)
※BU_CNT_CREDIT_PROLONG_max,BU_CNT_CREDIT_PROLONG_latest
bureau_balance.csv　STATUS(信用情報機関のローンの月間ステータス
※BU_BB_STATUS_C_RATIO_max,BU_BB_STATUS_X_RATIO_max,BU_BB_STATUS_NUM_MAX_max
（ C：クローズ、X：ステータス不明、0：DPDなし、1：月間最大DPDが1-30、2：DPDが31-60、…5：DPDが120以上、または売却または償却済み]）)
'''

# --- 属性・職歴・地域評価に関連するカラム ---
client_background_cols1 = [
    'CNT_CHILDREN',               # 子供の数
    'DAYS_BIRTH',                 # 年齢（日換算）
    'DAYS_EMPLOYED',              # 勤続年数（日換算）
    'REGION_RATING_CLIENT',       # 住居の地域評価
    'REGION_RATING_CLIENT_W_CITY',# 住居の都市評価
]

# --- 提出書類・照会履歴（行動ログ）に関連するカラム ---
# FLAG_DOCUMENT_2〜21 を一括生成
document_cols = [f'FLAG_DOCUMENT_{i}' for i in range(2, 22)]

# 信用情報機関への照会件数（直近の動き）
enquiry_history_cols = [
    'AMT_REQ_CREDIT_BUREAU_HOUR',
    'AMT_REQ_CREDIT_BUREAU_DAY',
    'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON',
    'AMT_REQ_CREDIT_BUREAU_QRT',
    'AMT_REQ_CREDIT_BUREAU_YEAR'
]

# --- 信用情報（bureau/balance）の延滞・深刻度に関連するカラム ---
bureau_risk_cols = [
    'BU_CREDIT_DAY_OVERDUE_max',
    'BU_CREDIT_DAY_OVERDUE_latest',
    'BU_CNT_CREDIT_PROLONG_max',
    'BU_CNT_CREDIT_PROLONG_latest',
    'BU_BB_STATUS_C_RATIO_max',
    'BU_BB_STATUS_X_RATIO_max',
    'BU_BB_STATUS_NUM_MAX_max'
]


client_background_cols_summary = get_stats_summary(train, client_background_cols1)
print("【属性・職歴・地域評価に関連するカラム】")
print(client_background_cols_summary)
print("*"*100)
document_cols_summary = get_stats_summary(train, document_cols)
print("【提出書類・照会履歴（行動ログ）に関連するカラム】")
print(document_cols_summary)
print("*"*100)
enquiry_history_summary = get_stats_summary(train, enquiry_history_cols)
print("【信用情報機関への照会件数（直近の動き）】")
print(enquiry_history_summary)
print("*" * 100)
bureau_risk_summary = get_stats_summary(train, bureau_risk_cols)
print("【信用情報（bureau/balance）の延滞・深刻度に関連するカラム】")
print(bureau_risk_summary)
print("*" * 100)

"""
*   DAYS_EMPLOYED
にマイナスとプラスが混在しており、データとして異常であるため要分布確認
*   AMT_REQ_CREDIT_BUREAU_QRT
最大値が261と年間MAX25と比して異常であるため要分布確認

"""

#6-2 人物的評価　ヒストグラム(DAYS_EMPLOYED,AMT_REQ_CREDIT_BUREAU_QRT)
# 背景とフォントサイズの設定
sns.set_style("whitegrid", {'grid.linestyle': '--'})
plt.rcParams['font.size'] = 4

fig, ax = plt.subplots(2, 1, figsize=(6, 6))
my_palette = {0: "#74a9cf", 1: "#feb24c"}

# --- 1. DAYS_EMPLOYED ---
sns.histplot(data=train, x='DAYS_EMPLOYED', hue='TARGET', bins=100,
             ax=ax[0], multiple='layer', palette=my_palette, alpha=0.6, edgecolor='black')
ax[0].set_yscale('log')
ax[0].set_title('DAYS_EMPLOYED')
ax[0].set_xlabel('Days (Negative=Employed, 365243=Anomaly)')
ax[0].legend(title='TARGET', labels=['1 (Default)', '0 (Normal)'])

# --- 2. AMT_REQ_CREDIT_BUREAU_QRT ---
sns.histplot(data=train, x='AMT_REQ_CREDIT_BUREAU_QRT', hue='TARGET', bins=100,
             ax=ax[1], multiple='layer', palette=my_palette, alpha=0.6, edgecolor='black')
ax[1].set_yscale('log')
ax[1].set_title('AMT_REQ_CREDIT_BUREAU_QRT')
ax[1].set_xlabel('Enquiry Count (Last 3 Months)')
ax[1].legend(title='TARGET', labels=['1 (Default)', '0 (Normal)'])
ax[1].set_xticks(np.arange(0, 301, 15))

plt.tight_layout()
plt.show()

"""

*   DAYS_EMPLOYED  
概ね0以下で分布している。異常値365243は誤入力にしては件数が多いため、なんらかのシグナルであると思われる。
*   AMT_REQ_CREDIT_BUREAU_QRT  
件数が10^0であるため、誤入力の可能性が高い。
"""

#6-3 人物的評価　カテゴリ型の基本情報

client_background_cols2=[
    'NAME_TYPE_SUITE',            # ローン申請時の同行者
    'NAME_INCOME_TYPE',           # 収入タイプ（自営業、会社員等）
    'NAME_EDUCATION_TYPE',        # 学歴
    'NAME_FAMILY_STATUS',         # 家族構成
    'OCCUPATION_TYPE',            # 職業
    'ORGANIZATION_TYPE'           # 勤務先の業種
]

analyze_category_risk(train,client_background_cols2)

"""*   NAME_TYPE_SUITE  
配偶者や子連れのデフォルト率は7%台であり、比較的リスクが少ない傾向。  
単身者は構成比が最も高く全体の8割であり、デフォルト率は8.18%であった。  
複数人や、他人Aタイプ、他人Bタイプは構成比1%未満であり、数は少ないもののデフォルト率は単身者を上回った。特に他人Bタイプは9.83%と最も高いデフォルト率となっている。  
  
*   NAME_INCOME_TYPE  
件数自体は少ないものの、産休や無職はそれぞれ40%と36.6%であり、突出して高いデフォルト率となった。  
  
*   NAME_EDUCATION_TYPE  
学歴が高いほど、デフォルト率が低下傾向。特に修士・博士課程ではかなり低く、1.83%となった。  
  
*   OCCUPATION_TYPE  
傾向的には高い知識・スキルを要する職種のほうがデフォルト率が低くなった。

FE追加事項



*   勤続日数/年齢(DAYS_EMPLOYED/DAYS_BIRTH)
*   ビン別のデフォルト率（AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY)  
※リーク対策：Out-of-Fold＋Smoothing)  
*   提出書類の合計値(FLAG_DOCUMENT_2～21)
*   異常値フラグ365243(DAYS_EMPLOYED)
*   異常値フラグ15以上(AMT_REQ_CREDIT_BUREAU_QRT)
*   デフォルト率の幾何平均(ORGANIZATION_TYPE,OCCUPATION_TYPE,NAME_INCOME_TYPE)  
職業・職種・学歴・インカムタイプ  
※0防止のため各カラムに0.001を加算して計算  
※リーク対策：Out-of-Fold＋Smoothing)
"""

#7-1　申告情報の整合性　欠損及び欠損及び基本統計量
'''
AMT_GOODS_PRICE(商品価格)-AMT_CREDIT(融資額)
DAYS_ID_PUBLISH(申請時の身分証更新日)
REG_REGION_NOT_LIVE_REGION(連絡先と居住地の相違フラグ)
FLAG_MOBIL(携帯番号の提供有無のフラグ)
FLAG_EMP_PHONE(勤務先の電話番号の提供有無のフラグ)
FLAG_WORK_PHONE(自宅の電話番号の提供有無のフラグ)
FLAG_CONT_MOBILE(携帯番号と連絡可否のフラグ)
FLAG_EMAIL(メールアドレスの提供有無があるかどうかのフラグ)
bureau.csv　CREDIT_DAY_OVERDUE(サンプルにおける関連ローン申請時点でのCBクレジットの延滞日数)
※BU_CREDIT_DAY_OVERDUE_max,BU_CREDIT_DAY_OVERDUE_latest
previous_application.csv　CODE_REJECT_REASON(前回の申請が却下された理由)
※PREV_CODE_REJECT_REASON_latest
'''
train['DIFF_GOODS_CREDIT'] = train['AMT_GOODS_PRICE'] - train['AMT_CREDIT']
false_features1 = [
    'DIFF_GOODS_CREDIT',           # AMT_GOODS_PRICE - AMT_CREDIT
    'DAYS_ID_PUBLISH',             # 申請時の身分証更新日
    'BU_CREDIT_DAY_OVERDUE_max',   # 他社借入の最大延滞日数
    'BU_CREDIT_DAY_OVERDUE_latest',# 他社借入の直近延滞日数
]

false_features1_summary = get_stats_summary(train,false_features1)
print(false_features1_summary)

#7-2　申告情報の整合性　ヒストグラム

custom_palette = {0: "skyblue", 1: "orange"}

plt.figure(figsize=(16, 12))
plt.subplots_adjust(hspace=0.4)

for i, col in enumerate(false_features1, 1):
    plt.subplot(2, 2, i)

    # paletteに辞書を渡すことで、値を直接指定
    sns.histplot(data=train, x=col, hue='TARGET',
                 stat="density", common_norm=False, bins=30, #カウントだとデフォルトが見づらいため密度表示
                 palette=custom_palette, alpha=0.5) # alphaで透明度を調整すると重なりが見やすい

    plt.title(f'{col}')
    plt.grid(True, alpha=0.3)

plt.show()

"""

*   DIFF_GOODS_CREDIT(商品価格 - 融資額)  
商品価格と融資額の差が0付近ではデフォルト確率密度が非デフォルト確率密度を下回っているが、差が大きくなるとデフォルト確率密度のほうが大きくなることから、商品価格以上に融資を受ける者へのリスクは高くなる。  
*   DAYS_ID_PUBLISH  
-3000(約8年)あたりからデフォルト確率密度が上回ることから、身分証の更新日が新しいほどデフォルトリスクは高まる。想定では更新日0付近で高くなると思われたが、-2000(約5年)ごろから非デフォルト確率密度との差はあまり変わらない。  
*   BU_CREDIT_DAY_OVERDUE_max', 'BU_CREDIT_DAY_OVERDUE_latest'  
分布が見えないため、100以上をクリップ止めし、0を除外して再表示

"""

plt.figure(figsize=(16, 6))

overdue_cols = ['BU_CREDIT_DAY_OVERDUE_max', 'BU_CREDIT_DAY_OVERDUE_latest']

for i, col in enumerate(overdue_cols, 1):
    plt.subplot(1, 2, i)

    # 【重要】0日を除外して、1日以上の人だけに絞る
    subset = train[train[col] > 0].copy()
    subset[col] = subset[col].clip(upper=100) # 100日でクリップ

    # 0日の人がいない状態でヒストグラムを描画
    sns.histplot(data=subset, x=col, hue='TARGET',
                 stat="density", common_norm=False, bins=30,
                 palette={0: "skyblue", 1: "orange"}, alpha=0.6)

    plt.title(f'Overdue Users Only (>0 days): {col}')
    plt.xlabel('Days Overdue (Clipped at 100)')
    plt.grid(True, alpha=0.3)

plt.show()

"""当初は他社借入の延滞日数が大きくなるほどデフォルトしやすくなると想定していたが、あまり明確な差は得られなかった。"""

#7-3　申告情報の整合性　カテゴリ型の基本情報

false_features2=[
    'PREV_CODE_REJECT_REASON_latest' # 前回申請の却下理由
]
analyze_category_risk(train,false_features2)

# '''
# ユニーク値
# ※公式のカラム説明にないため、以下はAIに分析させた記載である。そのため参考程度に留めておく
# 　　'XAP': '承認（Rejectionなし）: 前回申請が問題なく通った、または却下されていない状態',
#     'LIMIT': '限度額オーバー: 借入総額が年収制限や社内規定の枠を超えている（多重債務リスク）',
#     'SCO': 'スコア不足: 属性（職種・年収・年齢等）の数値化結果が合格基準に達しなかった',
#     'HC': 'ハイリスク顧客: 重大な延滞歴やブラックリスト等、審査部門による強い拒絶（要注意）',
#     'VERIFY': '確認不備: 在籍確認が取れない、書類の不整合、本人確認の失敗など',
#     'CLIENT': '顧客都合: 審査の途中で顧客自身がキャンセル、または手続きを中断した',
#     'SCOFR': '詐欺疑いスコア: 申請内容に虚偽の疑いがある、または不正検知に反応した（極めて高リスク）',
#     'XNA': 'データなし: 理由が記録されていない、またはシステム上の欠損',
#     'SYSTEM': 'システムエラー: 審査エンジンの不具合やメンテナンス等による却下'
# '''

"""構成比は多くないものの、SCOFRやSYSTEMはデフォルト率20%であり、高い確率でデフォルトしている。  
一方で欠損している場合のデフォルト率は最も低く5.96%であった。XAPが前回承認であるならば、欠損は初回申請だと想定される。
"""

#7-4　申告情報の整合性　フラグ型の基本情報

false_features3=[
    'REG_REGION_NOT_LIVE_REGION',  # 連絡先と居住地の相違フラグ
    'FLAG_MOBIL',                  # 携帯番号の提供有無
    'FLAG_EMP_PHONE',              # 勤務先の電話番号の提供有無
    'FLAG_WORK_PHONE',             # 自宅の電話番号の提供有無
    'FLAG_CONT_MOBILE',            # 携帯番号と連絡可否
    'FLAG_EMAIL',                  # メールアドレスの提供有無
]

summary_list = []

for col in false_features3:
    # 各フラグごとに、0と1で集計
    temp = train.groupby(col)['TARGET'].agg(['count', 'mean']).reset_index()

    # 構成比(%)とデフォルト率(%)の計算
    temp['ratio'] = temp['count'] / temp['count'].sum() * 100
    temp['default_rate'] = temp['mean'] * 100

    # カラム名を整える
    temp.columns = ['Value', '件数', 'デフォルト率', '構成比(%)', 'デフォルト率(%)']

    print(f"\n▼ カラム名: {col}")
    print("-" * 50)
    print(temp[['Value', '件数', '構成比(%)', 'デフォルト率(%)']].to_string(index=False))
    print("-" * 50)

"""*   REG_REGION_NOT_LIVE_REGION  
割合は低いものの、居住地と連絡先住所が異なる場合のデフォルト率9.3%であり、一致している場合の8.05%よりやや高い傾向が見られた。  
*   FLAG_EMP_PHONE  
想定とは異なり、勤務先の連絡先登録がない場合は5.40%であるのに比して、ある場合は8.66%と高い傾向が見られた。  
*   FLAG_WORK_PHONE(公式説明:Did client provide home phone (1=YES, 0=NO))  
自宅の番号登録がない場合は7.69%であり、ある場合は9.63%とやや高い傾向が見られた。こちらも想定とは異なる結果となった。

FE追加事項


1.   AMT_GOODS_PRICE(商品価格)-AMT_CREDIT(融資額)


1.   身分証更新日 - 年齢 (DAYS_ID_PUBLISH - DAYS_BIRTH)
2.   異常値フラグの合計


1.   ビン別デフォルト率  
train['DIFF_GOODS_CREDIT'] = train['AMT_GOODS_PRICE'] - train['AMT_CREDIT']  
DAYS_ID_PUBLISH  
※リーク対策：Out-of-Fold＋Smoothing)  
2.   ユニーク値別のデフォルト率  (PREV_CODE_REJECT_REASON_latest)  
※リーク対策：Out-of-Fold＋Smoothing)  
2.   フラグ別のデフォルト率(REG_REGION_NOT_LIVE_REGION,FLAG_EMP_PHONE,FLAG_WORK_PHONE)
"""

#8-1　その他　(同行者、年齢)
# NAME_TYPE_SUITE × age_group でデフォルト率を算出

df_plot = train.copy()

if 'age_group' not in df_plot.columns:
    # DAYS_BIRTHはマイナス表記なので、正の数にして365で割り年齢を出す
    df_plot['age'] = df_plot['DAYS_BIRTH'] / -365
    df_plot['age_group'] = (df_plot['age'] // 10 * 10).astype(int).astype(str) + 's'

col_x = 'NAME_TYPE_SUITE'
col_y = 'age_group'

res_suite = df_plot.pivot_table(
    index=col_x,
    columns=col_y,
    values='TARGET',
    aggfunc='mean'
) * 100

print(f"▼ {col_x} × 年齢層別 デフォルト率(%)")
print("-" * 80)
print(res_suite.round(2))

"""概ね、年齢とともにデフォルト率が逓減傾向にあり、年齢の傾向を一致するが、20代のグループのデフォルト率の高さと他人Aタイプの低さが顕著に表れている。

【補足】  
DAYS_BIRTH (年齢)  
-10000(27歳)まではデフォルト率増加し、以降は逓減傾向。-23750(65歳)から大きく減少。
"""

#8-2　その他　(同行者、直前1時間の照会有無)
# 欠損値がある場合、集計が偏るため 0 で埋める（またはそのままでも可）
df_plot['REQ_HOUR_CLIP'] = df_plot['AMT_REQ_CREDIT_BUREAU_HOUR'].fillna(0)

# 直前1時間の照会がある(1回以上)か、ない(0回)かでフラグ化
df_plot['IS_URGENT_REQ'] = df_plot['REQ_HOUR_CLIP'].apply(lambda x: 1 if x > 0 else 0)

# NAME_TYPE_SUITE × IS_URGENT_REQ でデフォルト率を算出
res_urgent = df_plot.pivot_table(
    index='NAME_TYPE_SUITE',
    columns='IS_URGENT_REQ',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示を整える
res_urgent.columns = ['件数(照会なし)', '件数(あり)', 'デフォルト率(なし)%', 'デフォルト率(あり)%']
res_urgent['デフォルト率(なし)%'] *= 100
res_urgent['デフォルト率(あり)%'] *= 100

print(f"▼ 同行者 × 直前1時間の照会有無 リスクマトリックス")
print("-" * 85)
print(res_urgent.round(2).sort_values('デフォルト率(あり)%', ascending=False))
print("-" * 85)

"""子連れや他人Aタイプの同行者は直前１時間の照会があるとデフォルト率が高い傾向あり。"""

#8-3　その他　(同行者、当日(24h内)の照会有無)
# 欠損値を0で埋め、当日の照会有無をフラグ化
df_plot['REQ_DAY_CLIP'] = df_plot['AMT_REQ_CREDIT_BUREAU_DAY'].fillna(0)
df_plot['IS_DAY_REQ'] = df_plot['REQ_DAY_CLIP'].apply(lambda x: 1 if x > 0 else 0)

# NAME_TYPE_SUITE × IS_DAY_REQ でデフォルト率を算出
res_day = df_plot.pivot_table(
    index='NAME_TYPE_SUITE',
    columns='IS_DAY_REQ',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示整理
res_day.columns = ['件数(なし)', '件数(あり)', 'デフォルト率(なし)%', 'デフォルト率(あり)%']
res_day['デフォルト率(なし)%'] *= 100
res_day['デフォルト率(あり)%'] *= 100

print(f"▼ 同行者 × 当日(24h内)の照会有無 リスクマトリックス")
print("-" * 85)
print(res_day.round(2).sort_values('デフォルト率(あり)%', ascending=False))
print("-" * 85)

"""当日中に照会がある場合の家族連れや子連れのデフォルト率は高い。"""

#8-4　その他　(住宅形態、人口密度別)
# 子供の数を 0, 1, 2, 3以上 の4区分に整理（外れ値の影響を防ぐ）
# 人口密度を5段階に分割
df_plot['pop_group'] = pd.qcut(df_plot['REGION_POPULATION_RELATIVE'], 5, labels=['過疎', 'やや低', '中間', 'やや高', '密集'])

# 住宅形態 × 人口密度別 デフォルト率(%)
res_pop_house = df_plot.pivot_table(
    index='NAME_HOUSING_TYPE',
    columns='pop_group',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示整理
res_pop_house_mean = res_pop_house['mean'] * 100

print(f"▼ 住宅形態 × 人口密度別 デフォルト率(%)")
print("-" * 90)
print(res_pop_house_mean.round(2))
print("-" * 90)

"""想定とは異なり、密集地域でのデフォルト率は低く、中間地域が概ね高い傾向にある。また密度に比例せず、同一密度であっても住宅形態によって大きく差が出る結果となった。"""

#8-5　その他　(住宅形態、地域都市乗算値(1-9)別 デフォルト率(%))
# 1. 欠損値をそれぞれの平均値で補完
df_plot['REGION_RATING_CLIENT_fixed'] = df_plot['REGION_RATING_CLIENT'].fillna(df_plot['REGION_RATING_CLIENT'].mean())
df_plot['REGION_RATING_CLIENT_W_CITY_fixed'] = df_plot['REGION_RATING_CLIENT_W_CITY'].fillna(df_plot['REGION_RATING_CLIENT_W_CITY'].mean())

# 2. 乗算値の算出（1〜9の範囲になる）
df_plot['REGION_RATING_MUL'] = df_plot['REGION_RATING_CLIENT_fixed'] * df_plot['REGION_RATING_CLIENT_W_CITY_fixed']

# 3. 乗算値ごとのデフォルト率を集計
res_mul = df_plot.groupby('REGION_RATING_MUL')['TARGET'].agg(['count', 'mean'])
res_mul['mean'] *= 100

print("▼ 地域評価×都市評価（乗算値）別のデフォルト率(%)")
print("-" * 60)
print(res_mul.round(2).sort_index())
print("-" * 60)

# 乗算値（REGION_RATING_MUL）を整数型にして見やすくする（平均補完した場合は四捨五入）
df_plot['MUL_INT'] = df_plot['REGION_RATING_MUL'].round().astype(int)

# 住宅形態 × 乗算値（総合評価スコア）別 デフォルト率(%)
res_final = df_plot.pivot_table(
    index='NAME_HOUSING_TYPE',
    columns='MUL_INT',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示整理
res_final_mean = res_final['mean'] * 100

print(f"▼ 住宅形態 × 地域都市乗算値(1-9)別 デフォルト率(%)")
print("-" * 110)
print(res_final_mean.round(2))
print("-" * 110)

"""地域評価の乗算値においても単純な相関ではなく、3と6は高いが4は低くなる結果となった。"""

#8-6　その他　(組織形態、申請時間帯別 デフォルト率(%))
# 24時間を「早朝・深夜」「日中(勤務中)」「夕方・夜」に分ける
def get_time_slot(h):
    if 9 <= h <= 17: return '1:日中(9-17)'
    if 18 <= h <= 23: return '2:夜間(18-23)'
    return '0:早朝深夜(0-8)'

df_plot['time_slot'] = df_plot['HOUR_APPR_PROCESS_START'].apply(get_time_slot)

# 組織種別 × 時間帯別 デフォルト率(%)
res_org_time = df_plot.pivot_table(
    index='ORGANIZATION_TYPE',
    columns='time_slot',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示整理（デフォルト率が高い順に並べる）
res_org_time_mean = res_org_time['mean'] * 100
print(f"▼ 組織形態 × 申請時間帯別 デフォルト率(%)")
print("-" * 100)
print(res_org_time_mean.round(2).sort_values('1:日中(9-17)', ascending=False).head(20))
print("-" * 100)

"""概ね、早朝深夜にかけてはデフォルト率が高いが業種によっては低くなる場合もある。"""

#8-7　その他　(組織形態、申請時間帯別 デフォルト率(%))
# 職種 × 3時間帯別 デフォルト率(%)
res_occ_time = df_plot.pivot_table(
    index='OCCUPATION_TYPE',
    columns='time_slot',
    values='TARGET',
    aggfunc=['count', 'mean']
)

# 表示整理
res_occ_mean = res_occ_time['mean'] * 100

print(f"▼ 職種 × 申請時間帯別 デフォルト率(%)")
print("-" * 100)
# 全体のデフォルト率が高い順に並べて表示
print(res_occ_mean.round(2).sort_values('1:日中(9-17)', ascending=False))
print("-" * 100)

"""業種別では夜間は比較的デフォルト率が低い傾向があったが、職種では夜間の方が高くなるケースも見られた。

FE追加事項
*   同行者＋年齢層ビン(NAME_TYPE_SUITE＋20～60+)
*   同行者＋直前1時間の照会有無(NAME_TYPE_SUITE＋0～1)
*   同行者＋当日(24h内)の照会有無(NAME_TYPE_SUITE＋0～1)
*   住宅形態＋人口密度別ビン(NAME_HOUSING_TYPE＋過疎～密集)
*   住宅形態＋地域都市乗算値(1-9)(NAME_HOUSING_TYPE＋1～9)
*   業種＋申請時間ビン(ORGANIZATION_TYPE＋0～3)
*   職種＋申請時間ビン(OCCUPATION_TYPE＋0～3)

反省点  
手順5～7は観点別にカラムを目検整理してEDAを行ったが、組み合わせについては同属性(日数系、金額系など)がばらばらとなり、この規模での検討が困難に思われた。  
また、明確な線引きが難しく個人の裁量による部分がほとんどのため再現性もあまりないように思える。  
  
ただ、特徴量設計時における観点としてはやはり重要だと思われるため、今後はどういう手法で現実的に落とし込んでいくかが課題である。
"""