# -*- coding: utf-8 -*-
"""home-credit-default-risk_01_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Yy_C4x1xpHM1paQJkgNd7SJbz8Iczpc

Cleaning
"""

# Commented out IPython magic to ensure Python compatibility.
#0　基本設定

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# %matplotlib inline
# %config Inlinebackend.figure_format='retina'
sns.set(style='whitegrid')
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',100)

from google.colab import drive
drive.mount('/content/drive')

'''
クリーニング手順メモ
1 読み込み → 即ダウンキャスト、オブジェクト型の変換
2 各テーブル参照、マージ検討
3 テーブルマージ及び再ダウンキャスト
4 金額列だけfloat32→float64（桁あふれ対策）
5 モデル(LightGBM / CatBoost)試走
6 リーク検討
7 モデル再試走(リークがなければ省略)
8 両モデルでimportance=0の列を削除
なお、本データは削除せずFE後に試走し、不要カラムを削除
9 モデル再試走　影響度確認
10 parquet（zstd）出力
'''

#1-1　ダウンキャスト関数（int,float）

total_mem = 0
total_mem_r = 0

def reduce(df):
    global total_mem,total_mem_r

    """ 数値データの型を最適化してメモリを節約する関数 """
    start_mem=df.memory_usage().sum()/1024**2

    numeric_cols = df.select_dtypes(include=['number']).columns

    for col in numeric_cols:
        col_type = df[col].dtype
        cmin = df[col].min()
        cmax = df[col].max()

        if str(col_type)[:3]=='int':
            if   cmin > np.iinfo(np.int8).min and cmax < np.iinfo(np.int8).max:
              df[col]=df[col].astype(np.int8)
            elif cmin > np.iinfo(np.int16).min and cmax < np.iinfo(np.int16).max:
              df[col]=df[col].astype(np.int16)
            elif cmin > np.iinfo(np.int32).min and cmax < np.iinfo(np.int32).max:
              df[col]=df[col].astype(np.int32)
            else:
              df[col]=df[col].astype(np.int64)
        else:
            #if   cmin > np.finfo(np.float16).min and cmax < np.finfo(np.float16).max:
              #df[col]=df[col].astype(np.float16)
            #elif       今回はfloat16型不使用
            if   cmin > np.finfo(np.float32).min and cmax < np.finfo(np.float32).max:
              df[col]=df[col].astype(np.float32)
            else:
              df[col]=df[col].astype(np.float64)

    end_mem=df.memory_usage().sum()/1024**2
    print(f'メモリ使用量: {start_mem:.2f}MB -> {end_mem:.2f}MB | ',
          f'削減: {(start_mem - end_mem) / start_mem:.2f}MB {100*(start_mem - end_mem) / start_mem:.1f}%')
    total_mem +=start_mem
    total_mem_r +=end_mem
    return df

#1-2　csv読込→ダウンキャスト
application_train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/application_train.csv')
application_train=reduce(application_train) #メインテーブル train
application_test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/application_test.csv')
application_test=reduce(application_test) #メインテーブル test

bureau=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/bureau.csv')
bureau=reduce(bureau) #結合先：メイン、キー：SK_ID_CURR

bureau_balance=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/bureau_balance.csv')
bureau_balance=reduce(bureau_balance) #結合先：bureau、キー：SK_ID_BUREAU

previous_application=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/previous_application.csv')
previous_application=reduce(previous_application) #結合先：メイン、キー：SK_ID_CURR

POS_CASH_balance=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/POS_CASH_balance.csv')
POS_CASH_balance=reduce(POS_CASH_balance) #結合先：previous_application、キー：SK_ID_PREV

instalments_payments=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/installments_payments.csv')
instalments_payments=reduce(instalments_payments) #結合先：previous_application、キー：SK_ID_PREV

credit_card_balance=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/credit_card_balance.csv')
credit_card_balance=reduce(credit_card_balance) #結合先：previous_application、キー：SK_ID_PREV


total_reduce = total_mem - total_mem_r
total_ratio = 100 * (total_reduce/total_mem)
print('-'*20)
print(f'合計メモリ使用量：{total_mem:.2f}MB -> {total_mem_r:.2f}MB | ',
      f'合計削減: {(total_reduce):.2f}MB {(total_ratio):.2f}%')

'''
テーブル構造メモ
application_train/test（メイン）
  └─ SK_ID_CURR ─ bureau（他社借入履歴）
               │    └─ SK_ID_BUREAU ─ bureau_balance（月次残高）
               └─ previous_application（過去申請）
                     └─ SK_ID_PREV ─ POS_CASH_balance（月次残高）
                                　   ─ instalments_payments（返済履歴）
                             　      ─ credit_card_balance（CC残高）
'''

#1-3　各テーブル確認　(データ型の確認)

tables = {
    "application_train": application_train,
    "application_test": application_test,
    "bureau": bureau,
    "bureau_balance": bureau_balance,
    "previous_application": previous_application,
    "POS_CASH_balance": POS_CASH_balance,
    "instalments_payments": instalments_payments,
    "credit_card_balance": credit_card_balance
}

summary_data = []

for name, df in tables.items():
    type_counts = df.dtypes.value_counts()
    info = {
        "Table": name,
        "Total Columns": len(df.columns),
        "Rows": len(df)
    }
    for dtype, count in type_counts.items():
        info[str(dtype)] = info.get(str(dtype), 0) + count

    summary_data.append(info)

summary_df = pd.DataFrame(summary_data).fillna(0).astype({col: 'int' for col in summary_data[0].keys() if col != 'Table'})
summary_df

#1-4　データ型変換(オブジェクト→カテゴリ型)

for df in tables.values():
    obj_cols = df.select_dtypes(include='object').columns
    for col in obj_cols:
        df[col] = df[col].astype('category')

for name, df in tables.items():
    print(f"{name:25} | Object: {len(df.select_dtypes('object').columns)} | Category: {len(df.select_dtypes('category').columns)}")

#2-1　各テーブル参照、マージ検討  (bureau及びbureau_balance　キー：SK_ID_BUREAU)

for name in ["bureau", "bureau_balance"]:
    df = tables[name]
    print(f"\n" + "="*60)
    print(f"【Table: {name}】 Unique Value Analysis")
    print(f"="*60)

    for col in df.columns:
        unique_count = df[col].nunique()
        print(f"\n[Column: {col}]")
        print(f"  - Unique values: {unique_count}")

        # カテゴリ型、オブジェクト型、または種類が少ない数値型（フラグ等）の内訳を表示
        if df[col].dtype.name in ['category', 'object'] or unique_count < 15:
            print("  - Value counts:")
            print(df[col].value_counts(dropna=False).head(10)) # 上位10件
        else:
            # 連続値（金額など）の場合は、代表的な統計量を添える
            print(f"  - Min: {df[col].min()} | Max: {df[col].max()} | Mean: {df[col].mean():.2f}")
    print("\n")

# bureau (他社借入履歴)
print(f"\n{'='*50}\n【Table: bureau】\n{'='*50}")
print(tables['bureau'].head())

# bureau_balance (他社借入の月次残高)
print(f"\n{'='*50}\n【Table: bureau_balance】\n{'='*50}")
print(tables['bureau_balance'].head())

"""HEAD情報(bureau及びbureau_balance)より、同一キー番号のレコードが複数あることから、マージ時のデータ膨張を抑えるため集約を実施。

bureau_balanceのキー別集約  
*   STATUS  
    全件数、C件数、C率、X件数、X率  
    数値最大、数値平均、数値偏差、   
    直近のステータス
*   MONTHS_BALANCE  
    最小値、最大値、全件数
"""

#2-2　各テーブル参照、マージ検討  (bureau_balance　集約)

# 1. 準備：STATUSを数値評価用に変換（C, XはNaN、0〜5を数値化）
bb = tables['bureau_balance'].copy()
bb['STATUS_STR'] = bb['STATUS'].astype(str)
bb['STATUS_NUM'] = bb['STATUS_STR'].replace({'C': np.nan, 'X': np.nan}).astype(float)

# 2. 直近（MONTHS_BALANCEが最大）のステータスを取得
bb_latest = bb.sort_values(['SK_ID_BUREAU', 'MONTHS_BALANCE']).groupby('SK_ID_BUREAU').tail(1)
bb_latest = bb_latest[['SK_ID_BUREAU', 'STATUS_STR']].rename(columns={'STATUS_STR': 'BB_LATEST_STATUS'})

# 3. 集計実行
bb_agg = bb.groupby('SK_ID_BUREAU').agg(
    BB_STATUS_COUNT=('STATUS_STR', 'count'),
    BB_STATUS_C_COUNT=('STATUS_STR', lambda x: (x == 'C').sum()),
    BB_STATUS_X_COUNT=('STATUS_STR', lambda x: (x == 'X').sum()),
    BB_STATUS_NUM_MAX=('STATUS_NUM', 'max'),
    BB_STATUS_NUM_MEAN=('STATUS_NUM', 'mean'),
    BB_STATUS_NUM_STD=('STATUS_NUM', 'std'),
    BB_MONTHS_BALANCE_MIN=('MONTHS_BALANCE', 'min'),
    BB_MONTHS_BALANCE_MAX=('MONTHS_BALANCE', 'max'),
    BB_MONTHS_BALANCE_LEN=('MONTHS_BALANCE', 'count')
)

# 4. 率の計算 と 直近ステータスのマージ
bb_agg['BB_STATUS_C_RATIO'] = bb_agg['BB_STATUS_C_COUNT'] / bb_agg['BB_STATUS_COUNT']
bb_agg['BB_STATUS_X_RATIO'] = bb_agg['BB_STATUS_X_COUNT'] / bb_agg['BB_STATUS_COUNT']
bb_agg = bb_agg.reset_index().merge(bb_latest, on='SK_ID_BUREAU', how='left')

print(f"集約後の形状: {bb_agg.shape}")
print(bb_agg.head())

"""headだと0とNaNのみしか見れないため、一部確認を実施"""

#2-3　各テーブル参照、マージ検討  (bureau_balance　最大値確認)
bb_agg['BB_STATUS_NUM_MAX'].describe()

"""MAX値で加工できていることを確認"""

#2-4　各テーブル参照、マージ検討  結合キー確認
'''
application_train/test
previous_application(SK_ID_CURR,SK_ID_PREV)
POS_CASH_balance,instalments_payments,credit_card_balance(SK_ID_PREV)
'''
target_info = [
    ('application_train', 'SK_ID_CURR'),
    ('application_test', 'SK_ID_CURR'),
    ('previous_application', 'SK_ID_CURR'),
    ('previous_application', 'SK_ID_PREV'),
    ('POS_CASH_balance', 'SK_ID_PREV'),
    ('instalments_payments', 'SK_ID_PREV'),
    ('credit_card_balance', 'SK_ID_PREV'),
    ('bureau', 'SK_ID_CURR'),
    ('bureau', 'SK_ID_BUREAU'),
    ('bureau_balance','SK_ID_BUREAU')
]

print(f"{'Table':<25} | {'Key':<12} | {'Total Rows':>10} | {'Unique Keys':>10} | {'Repeat Rate'}")
print("-" * 80)

for table_name, key in target_info:
    df = tables[table_name]
    total_rows = len(df)
    unique_keys = df[key].nunique()
    repeat_rate = total_rows / unique_keys

    print(f"{table_name:<25} | {key:<12} | {total_rows:>10} | {unique_keys:>10} | {repeat_rate:.2f}")

"""【キー情報整理】  
*   メインテーブルのキー重複なし  
*   previous_application,bureau  
下流テーブルとのキーでは重複ないものの、メイン結合前に集約を要する  
*   POS_CASH_balance,instalments_payments,credit_card_balance  
キー重複しているため集約を要する
  
  下流から順に集約を実施  
  ※階層順に集約→マージ→集約  
  　中間テーブルを下流テーブルとのマージ前に集約すると下流とのIDごと集約されてマージできなくなるため。

【サブテーブル(bureau_balance除く)のキー別集約　方向性】  
  
メインテーブル除くカラム数が100程度あることから  
集約時点でのカラムの深度ある検討は困難と判断。  
以下の集約処理を関数化し、一律実行を行う。
1.   カテゴリ型  
     ユニーク数、直近値
2.   数値型  
     最小、最大、平均、合計、標準偏差 、直近値  


なお、モデル実装後に更なる精度向上を図る場合においては寄与度やSHAPで重要度の高いもの、目検におけるカラム特性において有効度の高そうなものについて再考を実施。  

【修正事項】
*   カテゴリ型の最頻値については処理時間上、一旦除外して行う。
*   previous_applicationと下流テーブルをマージして集約するとセッションクラッシュするため、それぞれメインキーで集約して直接メインテーブルとマージを行う。
"""

#2-5　各テーブル参照、マージ検討  集約関数

def aggregate_table(df, group_key, sort_col, prefix=''):
    exclude = [group_key, sort_col]
    num_cols = [c for c in df.select_dtypes('number').columns if c not in exclude]
    cat_cols = [c for c in df.select_dtypes(['object', 'category']).columns if c not in exclude]

    # --- 数値型集約 ---
    num_agg = df.groupby(group_key)[num_cols].agg(['min', 'max', 'mean', 'sum', 'std'])
    num_agg.columns = [f'{prefix}{c}_{s}' for c, s in num_agg.columns]

    # --- カテゴリ型集約 ---
    if cat_cols:
        cat_agg = df.groupby(group_key)[cat_cols].agg(['nunique'])
        cat_agg.columns = [f'{prefix}{c}_{s}' for c, s in cat_agg.columns]
    else:
        cat_agg = pd.DataFrame(index=df[group_key].unique())

    # --- 直近値（sort_colが最大の行） ---
    latest = df.sort_values(sort_col).groupby(group_key).tail(1).set_index(group_key)
    latest_cols = {c: f'{prefix}{c}_latest' for c in num_cols + cat_cols}
    latest = latest[num_cols + cat_cols].rename(columns=latest_cols)

    # --- ソート列自体の集約 ---
    sort_agg = df.groupby(group_key)[sort_col].agg(['min', 'max', 'count'])
    sort_agg.columns = [f'{prefix}{sort_col}_{s}' for s in ['min', 'max', 'count']]

    # --- 結合 ---
    result = num_agg.join(cat_agg).join(latest).join(sort_agg).reset_index()
    return result

#2-6　各テーブル参照、マージ検討  第3階層　集約(POS_CASH_balance)
import gc
pos_agg = aggregate_table(POS_CASH_balance, 'SK_ID_CURR', 'MONTHS_BALANCE', prefix='POS_')
del POS_CASH_balance
gc.collect()
pos_agg.head()

#2-7　各テーブル参照、マージ検討  第3階層　集約(instalments_payments)
import gc
ins_agg = aggregate_table(instalments_payments, 'SK_ID_CURR', 'DAYS_INSTALMENT', prefix='INS_')
del instalments_payments
gc.collect()
ins_agg.head()

#2-8　各テーブル参照、マージ検討　第3階層　集約(credit_card_balance)
import gc
cc_agg = aggregate_table(credit_card_balance, 'SK_ID_CURR', 'MONTHS_BALANCE', prefix='CC_')
del credit_card_balance
gc.collect()
cc_agg.head()

#2-9　各テーブル参照、マージ検討 結合キー再確認
'''
application_train/test
previous_application(SK_ID_CURR,SK_ID_PREV)
POS_CASH_balance,instalments_payments,credit_card_balance(SK_ID_PREV)
'''
# テーブル名、データフレーム変数、チェックしたいキーをセットにする
target_agg = [
    ('application_train',    application_train,    'SK_ID_CURR'),
    ('application_test',     application_test,     'SK_ID_CURR'),
    ('previous_application', previous_application, 'SK_ID_CURR'),
    ('pos_agg',              pos_agg,              'SK_ID_CURR'),
    ('ins_agg',              ins_agg,              'SK_ID_CURR'),
    ('cc_agg',               cc_agg,               'SK_ID_CURR'),
    ('bureau',               bureau,               'SK_ID_CURR'),
    ('bureau',               bureau,               'SK_ID_BUREAU'),
    ('bb_agg',               bb_agg,               'SK_ID_BUREAU')
]

print(f"{'Table':<25} | {'Key':<12} | {'Total Rows':>10} | {'Unique Keys':>10} | {'Repeat Rate'}")
print("-" * 80)

for name, df, key in target_agg:
    total_rows = len(df)
    unique_keys = df[key].nunique()
    repeat_rate = total_rows / unique_keys

    print(f"{name:<25} | {key:<12} | {total_rows:>10} | {unique_keys:>10} | {repeat_rate:.2f}")

"""第2階層と第3階層のキー(SK_ID_BUREAU)が1対1であることを確認"""

#3-1　マージ 第2-3階層　bureau-bureaubalance　(SK_ID_BUREAU)

bureau = bureau.merge(bb_agg, on='SK_ID_BUREAU', how='left')
del bb_agg
gc.collect()

print(f"bureau shape: {bureau.shape}")

'''以下のマージ後のテーブルでは、メインキー集約時にセッションクラッシュのため使用不可'''

#　マージ　第2-3階層　previous_application-POS_CASH_balance,
#                                         -instalments_payments,
#                                         -credit_card_balance　(SK_ID_PREV)

# previous_application = previous_application.merge(pos_agg, on='SK_ID_PREV', how='left')
# del pos_agg
# previous_application = previous_application.merge(ins_agg, on='SK_ID_PREV', how='left')
# del ins_agg
# previous_application = previous_application.merge(cc_agg,  on='SK_ID_PREV', how='left')
# del cc_agg
# gc.collect()

# print(f"New previous_application shape: {previous_application.shape}")

#3-2　マージ　第2階層　集約(bureau)
import gc
bureau_agg = aggregate_table(bureau, 'SK_ID_CURR', 'DAYS_CREDIT', prefix='BU_')
del bureau
gc.collect()
bureau_agg.head()

#3-3　マージ　第2階層　集約(previous_application)

import gc
prev_agg = aggregate_table(previous_application, 'SK_ID_CURR', 'DAYS_DECISION', prefix='PREV_')
del previous_application
gc.collect()
prev_agg.head()

#3-4　マージ及びダウンキャスト　第1-2、第1-3階層
# application_train/test - bureau
#　    (SK_ID_CURR)        - previous_application
#                          -POS_CASH_balance,
#                          -instalments_payments,
#                          -credit_card_balance

application_train = application_train.merge(bureau_agg, on='SK_ID_CURR', how='left')
application_test  = application_test.merge(bureau_agg, on='SK_ID_CURR', how='left')
del bureau_agg
application_train = application_train.merge(prev_agg, on='SK_ID_CURR', how='left')
application_test  = application_test.merge(prev_agg, on='SK_ID_CURR', how='left')
del prev_agg
application_train = application_train.merge(pos_agg, on='SK_ID_CURR', how='left')
application_test  = application_test.merge(pos_agg, on='SK_ID_CURR', how='left')
del pos_agg
application_train = application_train.merge(ins_agg, on='SK_ID_CURR', how='left')
application_test  = application_test.merge(ins_agg, on='SK_ID_CURR', how='left')
del ins_agg
application_train = application_train.merge(cc_agg, on='SK_ID_CURR', how='left')
application_test  = application_test.merge(cc_agg, on='SK_ID_CURR', how='left')
del cc_agg

gc.collect()
application_train = reduce(application_train)
application_test  = reduce(application_test)

#4-1　AMTリサイズ(データ加工時の桁あふれ対策)

train_test_table = [application_train, application_test]
names = ["application_train", "application_test"]

for i, df in enumerate(train_test_table):
    amt_cols = df.filter(like='AMT').columns.tolist()

    if len(amt_cols) > 0:
        df[amt_cols] = df[amt_cols].astype(np.float64)

        print(f"Updated {names[i]}: {len(amt_cols)} columns converted to float64")
    else:
        continue

print("\n--- Check application_train types (AMT only) ---")
print(application_train.filter(like='AMT').dtypes.head())

# 5. メモリの最終確認
import gc
gc.collect()
print(f"\nTrain Memory: {application_train.memory_usage().sum() / 1024**2:.2f} MB")

#4-2　データ型再確認
# Train と Test の形状を確認
print(f"Train Shape: {application_train.shape}")
print(f"Test Shape:  {application_test.shape}")
# データ型の内訳を確認
print("Train Data Types Summary:")
print(application_train.dtypes.value_counts())
print(application_test.dtypes.value_counts())
# 初期行数: Train=307511, Test=48744

"""集約時にオブジェクト型が混ざったため、再変換"""

#4-3　オブジェクト変換
# 変換対象のデータフレームをリストにする
dfs = [application_train, application_test]

for df in dfs:
    # 各データフレームごとに object 型の列を抽出
    obj_cols = df.select_dtypes('object').columns
    # 抽出した列を一括で category 型に変換
    df[obj_cols] = df[obj_cols].astype('category')
    # 変換されたカラム名が数値型でないことの確認
    print(f"Converted columns: {list(obj_cols)}")

#5-1　モデル試走(LightGBM/CatBoost)　関数

!pip install catboost
import lightgbm as lgb
import catboost as cb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

# --- 2. [重要] drop_list の定義 ---
# カラム削除後の再利用のため
if 'drop_list' not in globals():
    drop_list = []

# --- 3. データの準備 ---
y = application_train['TARGET']
X = application_train.drop(columns=['TARGET', 'SK_ID_CURR'] + [c for c in drop_list if c in application_train.columns], errors='ignore')

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

categorical_features = X_train.select_dtypes(include=['category']).columns.tolist()

params = {
    'objective': 'binary',
    'metric': 'auc',
    'verbosity': -1,
    'boosting_type': 'gbdt',
    'random_state': 42,
    'learning_rate': 0.05,
    'n_estimators': 100
}

# --- 4. 関数の定義 ---
def run_lgb_trial(X_train, y_train, X_valid, y_valid, params):
    model = lgb.LGBMClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_valid, y_valid)],
        callbacks=[lgb.log_evaluation(period=0), lgb.early_stopping(stopping_rounds=50)]
    )
    auc = roc_auc_score(y_valid, model.predict_proba(X_valid)[:, 1])
    imp = pd.DataFrame({
        'feature': X_train.columns,
        'LGBM_pct': 100 * model.feature_importances_ / model.feature_importances_.sum()
    })
    return model, auc, imp

def run_cat_trial(X_train, y_train, X_valid, y_valid, categorical_features):
    xt_cb = X_train.copy()
    xv_cb = X_valid.copy()
    for col in categorical_features:
        xt_cb[col] = xt_cb[col].astype(str).replace('nan', 'Unknown')
        xv_cb[col] = xv_cb[col].astype(str).replace('nan', 'Unknown')

    model = cb.CatBoostClassifier(
        iterations=300, learning_rate=0.05, depth=6, eval_metric='AUC',
        random_seed=42, logging_level='Silent',
        cat_features=categorical_features, task_type='CPU'
    )
    model.fit(xt_cb, y_train, eval_set=(xv_cb, y_valid), early_stopping_rounds=50)
    auc = roc_auc_score(y_valid, model.predict_proba(xv_cb)[:, 1])
    imp = pd.DataFrame({
        'feature': X_train.columns,
        'CAT_pct': 100 * model.get_feature_importance() / model.get_feature_importance().sum()
    })
    return model, auc, imp

#5-2　モデル試走(LightGBM/CatBoost)　試走
print(" LightGBM 試走開始")
lgb_model, lgb_auc, lgb_imp = run_lgb_trial(X_train, y_train, X_valid, y_valid, params)

print(" CatBoost 試走開始")
cat_model, cat_auc, cat_imp = run_cat_trial(X_train, y_train, X_valid, y_valid, categorical_features)

print(f"\n 試走完了 AUC - LGBM: {lgb_auc:.4f} / CatBoost: {cat_auc:.4f}")

#5-3　モデル試走(LightGBM/CatBoost)　試走結果
# --- 3. 比較用データの作成 ---

# マージして比較表を作成
comparison_df =pd.merge(lgb_imp, cat_imp, on='feature').sort_values(by='LGBM_pct', ascending=False)

# --- 4. 結果表示 ---
print(f"　 精度比較 (AUC):")
print(f"  - LightGBM: {lgb_auc:.4f}")
print(f"  - CatBoost: {cat_auc:.4f}\n")

# LGBMのTOP15
lgb_top15 = comparison_df.sort_values(by='LGBM_pct', ascending=False).head(15)[['feature', 'LGBM_pct']]
lgb_top15.columns = ['LGBM Feature', 'Importance(%)']

# CatBoostのTOP15
cb_top15 = comparison_df.sort_values(by='CAT_pct', ascending=False).head(15)[['feature', 'CAT_pct']]
cb_top15.columns = ['CatBoost Feature', 'Importance(%)']

# インデックスをリセットして横に並べる
lgb_top15 = lgb_top15.reset_index(drop=True)
cb_top15 = cb_top15.reset_index(drop=True)
side_by_side = pd.concat([lgb_top15, cb_top15], axis=1)

print(" モデル別インポータンス TOP 15")
print(side_by_side.to_markdown(index=False))

# --- 共通の注目株 ---
common_top = set(lgb_top15['LGBM Feature']) & set(cb_top15['CatBoost Feature'])
print(f"\n 両モデルが共通してTOP15に挙げた項目: {len(common_top)}件")
print(list(common_top))

#6-1　リークの検討
'''
割合としては特段強いシグナルを持つカラムはなく、
5％を超えるものとしては外部データ(EXT_SOURCE)と職業( ORGANIZATION_TYPE)であり、リークではないと判断。
'''
#7-1　モデル再試走
'''
リークはないと判断したため、手順省略
'''

#8-1　両モデル共通の寄与度0カラム削除(X_train,X_valid)

# --- 1. 不要列リストの確定 ---
common_zero = comparison_df[(comparison_df['LGBM_pct'] == 0) & (comparison_df['CAT_pct'] == 0)]
drop_list = common_zero['feature'].tolist()
print(f" 共通寄与度0の項目数: {len(drop_list)} / {len(comparison_df)}")

# --- 2. 全データセット（Train/Valid/Test）から一括ドロップ ---
# X_test が定義されていることを前提としています
X_train = X_train.drop(columns=drop_list)
X_valid = X_valid.drop(columns=drop_list)

# テストデータも同様に処理（もし既に存在すれば）
if 'X_test' in globals():
    X_test = X_test.drop(columns=drop_list)
    print(" X_test 不要列削除")

# カテゴリ変数リストも同期
categorical_features = [c for c in categorical_features if c in X_train.columns]

# --- 3. 最終結果の確認 ---
print("-" * 30)
print(f" 削除されたカラム数: {len(drop_list)}")
print(f" スリム化後のカラム数 (X_train): {X_train.shape[1]}")
if 'X_test' in globals():
    print(f" スリム化後のカラム数 (X_test) : {X_test.shape[1]}")
print(f" カテゴリ変数リストの残り数: {len(categorical_features)}")
print("-" * 30)

# 削除対象された特徴量の全リストを確認
print(f"削除された特徴量の数: {len(drop_list)}")
print("-" * 30)

for i in range(0, len(drop_list), 5):
    # 5つずつスライスして取り出す
    chunk = drop_list[i:i+5]
    print("".join(f"{col:<30}" for col in chunk))

#9-1　モデル再試走(LightGBM/CATBoost)

current_cols = X_train.shape[1]
print(f"\n LightGBM ({current_cols}列) 試走開始")
lgb_model, lgb_auc, lgb_imp = run_lgb_trial(X_train, y_train, X_valid, y_valid, params)

print(f"\n CatBoost ({current_cols}列) 試走開始")
cat_model, cat_auc, cat_imp = run_cat_trial(X_train, y_train, X_valid, y_valid, categorical_features)

print("\n" + "="*30)
print(f" 再試走スコア (AUC)")
print(f"  - LightGBM : {lgb_auc:.4f}")
print(f"  - CatBoost  : {cat_auc:.4f}")
print("="*30)

#9-2　モデル再試走(LightGBM/CatBoost)　試走結果
# --- 3. 比較用データの作成 ---

# マージして比較表を作成
comparison_df =pd.merge(lgb_imp, cat_imp, on='feature').sort_values(by='LGBM_pct', ascending=False)

# --- 4. 結果表示 ---
print(f" 精度比較 (AUC) [スリム版]:")
print(f"  - LightGBM: {lgb_auc:.4f}")
print(f"  - CatBoost: {cat_auc:.4f}\n")

# LGBMのTOP15
lgb_top15_s = comparison_df.sort_values(by='LGBM_pct', ascending=False).head(15)[['feature', 'LGBM_pct']]
lgb_top15_s.columns = ['LGBM Feature', 'Importance(%)']

# CatBoostのTOP15
cb_top15_s = comparison_df.sort_values(by='CAT_pct', ascending=False).head(15)[['feature', 'CAT_pct']]
cb_top15_s.columns = ['CatBoost Feature', 'Importance(%)']

# インデックスをリセットして横に並べる
lgb_top15_s = lgb_top15_s.reset_index(drop=True)
cb_top15_s = cb_top15_s.reset_index(drop=True)
side_by_side_s = pd.concat([lgb_top15_s, cb_top15_s], axis=1)

print(" モデル別インポータンス TOP 15 (436列版)")
print(side_by_side_s.to_markdown(index=False))

# --- 共通 ---
common_top_s = set(lgb_top15_s['LGBM Feature']) & set(cb_top15_s['CatBoost Feature'])
print(f"\n 両モデルが共通してTOP15に挙げた項目: {len(common_top_s)}件")
print(sorted(list(common_top_s)))

"""寄与度整理
*   第1有力指標 (5%以上)  
共通： EXT_SOURCE_1～3 (外部機関によるスコア)  
LGBM： ORGANIZATION_TYPE (勤務先の業種)  

*   第2有力指標 (2～5%)  
共通： AMT_ANNUITY (ローンの年間支払い額)  
LGBM： INS_AMT_PAYMENT_min, BU_DAYS_CREDIT_max, AMT_CREDIT  
CAT： DAYS_BIRTH (年齢), AMT_GOODS_PRICE, CODE_GENDER  

*   その他 (重要度TOP 15圏内、上記との重複除く)  
共通：INS_AMT_PAYMENT_sum (分割払いの総支払額)  
LGBM：  
　OWN_CAR_AGE (所有車の年数)  
　INS_DAYS_ENTRY_PAYMENT_std (支払い日のバラつき/遅延傾向)  
　POS_SK_DPD_DEF_mean (POSローンの延滞日数)  
　CC_CNT_DRAWINGS_ATM_CURRENT_mean (クレカのATM引き出し回数)  
CAT：  
　NAME_EDUCATION_TYPE (学歴)  
　DAYS_EMPLOYED (就業日数)  
　OCCUPATION_TYPE (職種)  
　BU_AMT_CREDIT_SUM_DEBT_mean (現在の負債残高平均)

EDA、FEでは基本的事項に加え、上記の有力とされる指標から優先的に実施を行う。また、第2指標までは組合せ等も検討していきたい。
"""

#10-1　出力　parquet(zstd形式)
# zstd圧縮で保存
'''
EDAで使用するため、データ本体からの削除はFE後に再度試走して不要カラムの削除を行う。
'''
application_train.to_parquet('application_train_cleaning.zstd.parquet', compression='zstd', index=False)
application_test.to_parquet('application_test_cleaning.zstd.parquet', compression='zstd', index=False)

import os
train_size_zstd = os.path.getsize('application_train_cleaning.zstd.parquet') / 1024**2
print(f"Trainファイルサイズ (zstd): {train_size_zstd:.2f} MB")