# -*- coding: utf-8 -*-
"""home_credit_default_risk_02_EDA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd3lcBST05pqna5wek6XjYz36pVGEQuR
"""

# Commented out IPython magic to ensure Python compatibility.
#0-1　基本設定

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings

# %matplotlib inline
# %config Inlinebackend.figure_format='retina'
sns.set(style='whitegrid')
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',100)

from google.colab import drive
drive.mount('/content/drive')

#0-2 データ読込
train=pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/01クリーニング/application_train_cleaning.zstd.parquet')
test =pd.read_parquet('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/加工データ/01クリーニング/application_test_cleaning.zstd.parquet')

instalments_payments=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/home-credit-default-risk/原データ/installments_payments.csv')

print(f"Memory Usage: {train.memory_usage().sum() / 1024**2:.2f} MB")
train.head()

'''
EDA方針メモ
1 基本EDA (均衡度、欠損確認、統計量)
2 ターゲット変数(返済Y回目、遅延X日)
3 試走結果に基づくEDA(第1有力指標)
4 試走結果に基づくEDA(第2有力指標)
5 返済能力(借入、収入、支出)
6 人物的評価
7 申告情報の整合性
8 その他(目検で気になるものあれば)
'''

#1-1 基本EDA (均衡度)

# 1. 集計
summary = train.groupby('TARGET')['AMT_CREDIT'].agg(['count', 'sum'])

# 2. 比率を計算
summary['count_pct'] = (summary['count'] / summary['count'].sum()) * 100
summary['sum_pct']   = (summary['sum'] / summary['sum'].sum()) * 100

# 3. カラム名を日本語に変更（ここで名前が変わります）
summary.columns = ['件数', '借入総額', '件数比率(%)', '金額比率(%)']

# 4. 表示用のデータフレーム作成
display_df = summary.copy()
display_df['借入総額(千万)'] = display_df['借入総額'] / 10**7

# カラムの順番整理
display_df = display_df[['件数', '件数比率(%)', '借入総額(千万)', '金額比率(%)']]

# 表示用のコピー作成
styler_df = display_df.copy()

# HTMLテーブルとして整形（色付け処理を削除）
styler_df.style.format({
    '件数': '{:,} 件',
    '件数比率(%)': '{:.2f} %',
    '借入総額(千万)': '{:,.0f} 千万円',
    '金額比率(%)': '{:.2f} %'
}).set_caption("ターゲット別 信用リスクサマリー") \
  .set_table_styles([{'selector': 'th', 'props': [('text-align', 'center')]}])

"""不均衡度8.07％  
なお、デフォルト件数の比率よりも金額比率のほうが小さいことから、小口の方がデフォルトリスクが高い傾向にある。
"""

#1-2 基本EDA (欠損値)

# 表示設定
pd.options.display.float_format = '{:.2f}'.format

for df, title in [(train, "Train Data"), (test, "Test Data")]:
    # 統計計算
    total_cols = len(df.columns)
    missing_counts = df.isnull().sum()
    missing_cols_count = (missing_counts > 0).sum()
    no_missing_cols = df.columns[missing_counts == 0].tolist()
    no_missing_cols_count = len(no_missing_cols)

    # 欠損ありの詳細（上位15）
    missing_pct = (missing_counts / len(df)) * 100
    stats_df = pd.concat([missing_counts, missing_pct], axis=1)
    stats_df.columns = ['欠損数', '欠損割合(%)']
    top_15 = stats_df.sort_values('欠損割合(%)', ascending=False).head(15)

    # 出力
    print(f"\n{'='*20} {title} {'='*20}")
    print(f"全カラム数        : {total_cols}")
    print(f"欠損ありカラム数  : {missing_cols_count}")
    print(f"欠損なしカラム数  : {no_missing_cols_count}")

    print(f"\n--- 欠損割合：上位15 ---")
    print(top_15)

    print(f"\n--- 欠損なしカラム一覧 ---")
    for i in range(0, len(no_missing_cols), 5):
        print(", ".join(no_missing_cols[i:i+5]))

#1-3 基本EDA (統計量)

# --- 表示設定の変更 ---
pd.options.display.float_format = '{:.2f}'.format
# 行の省略を解除（400以上なら500に設定）
pd.set_option('display.max_rows', 500)

# --- 1. 数値データの統計量 ---
print(f"{'='*20} 数値データの統計量 (int, float) {'='*20}")
num_desc = train.select_dtypes(include=['number']).describe().T

# 全行表示
display(num_desc)

# --- 2. カテゴリデータの統計量 ---
print(f"\n{'='*20} カテゴリデータの統計量 (category) {'='*20}")
cat_desc = train.select_dtypes(include=['category']).describe().T
display(cat_desc)

"""全カラムの検討は現実的でないため、以下に方向修正  

*   以後のEDAにおいて確認したいもののみ精査
*   外れ値においては、明らかな異常値のみ抽出を行い、フラグ追加を実施。  
外れ値自体がシグナルの可能性を考慮して欠損化や削除は極力行わない方針とする。

"""

#1-4 基本EDA (異常値)

# 数値型カラムのみ対象
num_df = train.select_dtypes(include=['number'])

# 1. 統計量の計算（Q95とMax）
Q95 = num_df.quantile(0.95)
Max = num_df.max()
Mean = num_df.mean()
Q50 = num_df.quantile(0.50)

# 2. Max / Q95 比率を計算
# Q95が0の場合、除算エラーを避けるため微小値を加算
ratios = Max / (Q95 + 1e-9)

# 3. サマリーの作成
outlier_summary = pd.DataFrame({
    'Max/Q95比': ratios,
    '最大値': Max,
    '95%点': Q95,
    '中央値': Q50,
    '平均': Mean
})

# --- 判定基準 ---
# 比率が 100倍 を超えるものを「不自然な跳ね上がり」として抽出
# かつ、最大値、95％値が0でないもの
condition = (outlier_summary['Max/Q95比'] > 100) & (outlier_summary['最大値'] != 0) & (outlier_summary['95%点'] != 0)
outlier_summary = outlier_summary[condition].sort_values('Max/Q95比', ascending=False)

print(f"不自然な跳ね上がりが見つかったカラム数: {len(outlier_summary)} / {len(num_df.columns)}")
display(outlier_summary)

"""FE追加事項  
上記54カラムに対して以下を実施。
1.   Max/95％タイル値
2.   abnormal_MAX_frag(上記1.が100を超えるものを'1'、その他'0')  
※テストデータへの適用時に95％タイル値はトレインデータの値を使用すること。
"""

#2-1　ターゲット変数(X日)　installments_paymentsへのターゲット変数結合
'''
以下のとおり、返済の遅延開始と遅延日数についてはマスクされているため確認を行う
　「目的変数（1 - 支払い困難を抱える顧客：サンプル中のローンの最初のY回の分割払いのうち、
　　少なくとも1回でX日以上支払いが遅れた顧客、0 - その他のすべてのケース）」

以下の算式をもって検討
X日：installments_payments　（DAYS_ENTRY_PAYMENT - DAYS_INSTALMENT）　支払日-期限日
'''
# 1. train から必要な列（キーとターゲット）だけを抽出
target_map = train[['SK_ID_CURR', 'TARGET']]

# 2. instalments_payments に TARGET を結合（左結合：left join）
# ※ instalments_payments の全行を残しつつ、顧客IDが一致する TARGET を紐づけ
instalments_payments = instalments_payments.merge(target_map, on='SK_ID_CURR', how='left')

# 3. ターゲットが紐づかない行（testデータに含まれる顧客など）をどうするか確認
print(f"結合後の行数: {len(instalments_payments)}")
print(f"TARGETが欠損している行数: {instalments_payments['TARGET'].isnull().sum()}")

# 分析のために、TARGETが判明している（trainに含まれる）データだけに絞り込む
ins_train = instalments_payments.dropna(subset=['TARGET']).copy()
ins_train['TARGET'] = ins_train['TARGET'].astype(int) # floatをintに直す

print(f"分析対象の行数: {len(ins_train)}")

#2-2　基本EDA　ターゲット変数(X日)　遅延日数(DPD)ヒストグラム
# 1. 支払遅延日数(DPD)を計算
ins_train['DPD'] = ins_train['DAYS_ENTRY_PAYMENT'] - ins_train['DAYS_INSTALMENT']

# 2. 顧客ごとに最大値を抽出（一旦変数に代入）
user_max_dpd = ins_train.groupby('SK_ID_CURR')['DPD'].max().reset_index()

# 3. TARGETと結合
analysis_raw_df = user_max_dpd.merge(train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

# 4. 可視化
plt.figure(figsize=(6, 4))
# 変数名を DPD に統一
sns.histplot(data=analysis_raw_df[(analysis_raw_df['DPD'] >= -50) & (analysis_raw_df['DPD'] <= 120)],
             x='DPD', hue='TARGET',
             bins=85, element='step', common_norm=False, stat='density', alpha=0.5)

# 0日のライン（遅延の境界）
plt.axvline(x=0, color='black', linestyle='-', alpha=0.5, label='On-time (0)')

plt.title('Distribution of Maximum Delay Days per Customer (Raw Max DPD)')
plt.xlabel('Max DPD (Negative values indicate early payment)')
plt.ylabel('Density')
plt.legend(title='TARGET')
plt.grid(axis='y', alpha=0.3)
plt.show()

#2-3　ターゲット変数(X日)　DPD統計量

# 1. ターゲットを紐付けた一時的なデータフレームを作成
# メモリ節約のため必要な列だけ抽出
cols = ['DAYS_ENTRY_PAYMENT', 'DAYS_INSTALMENT', 'DPD']
tmp = ins_train[cols + ['SK_ID_CURR']].merge(train[['SK_ID_CURR', 'TARGET']], on='SK_ID_CURR', how='left')

# 2. カラムごとに TARGET別の統計量を算出
analysis_results = []

for col in cols:
    # TARGETごとに 件数(count:非欠損数) と 欠損率 を計算
    res = tmp.groupby('TARGET')[col].agg([
        ('Valid_Count', 'count'),
        ('Missing_Rate', lambda x: x.isnull().mean())
    ])
    res['Column'] = col
    analysis_results.append(res)

# 結合して見やすく表示
df_null_analysis = pd.concat(analysis_results).reset_index()
df_null_analysis = df_null_analysis[['Column', 'TARGET', 'Valid_Count', 'Missing_Rate']]

print("=== Column-wise Analysis by TARGET ===")
print(df_null_analysis.to_string(index=False))

"""XYターゲット索敵まとめ  
　当初、XとYはマスクされた定数データと考えていたが有意差が見られなかった。  
　また、遅延日数がマイナスにも関わらずデフォルト判定されている分布については、他社借入でデフォルトしたケース等が考えられる。  
よって、目的変数のXY値の推定は困難であると判断。

"""

#試走結果に基づくEDA
'''
寄与度整理

第1有力指標 (5%以上)
共通： EXT_SOURCE_1～3 (外部機関によるスコア)
LGBM： ORGANIZATION_TYPE (勤務先の業種)

第2有力指標 (2～5%)
共通： AMT_ANNUITY (ローンの年間支払い額)
LGBM： INS_AMT_PAYMENT_min, BU_DAYS_CREDIT_max, AMT_CREDIT
CAT： DAYS_BIRTH (年齢), AMT_GOODS_PRICE, CODE_GENDER

その他 (重要度TOP 15圏内、上記との重複除く)
共通：INS_AMT_PAYMENT_sum (分割払いの総支払額)
LGBM：
　OWN_CAR_AGE (所有車の年数)
　INS_DAYS_ENTRY_PAYMENT_std (支払い日のバラつき/遅延傾向)
　POS_SK_DPD_DEF_mean (POSローンの延滞日数)
　CC_CNT_DRAWINGS_ATM_CURRENT_mean (クレカのATM引き出し回数)
CAT：
　NAME_EDUCATION_TYPE (学歴)
　DAYS_EMPLOYED (就業日数)
　OCCUPATION_TYPE (職種)
　BU_AMT_CREDIT_SUM_DEBT_mean (現在の負債残高平均)
'''

'''
 精度比較 (AUC) [スリム版]:
  - LightGBM: 0.7771
  - CatBoost: 0.7820

 モデル別インポータンス TOP 15 (436列版)
| LGBM Feature                     |   Importance(%) | CatBoost Feature            |   Importance(%) |
|:---------------------------------|----------------:|:----------------------------|----------------:|
| ORGANIZATION_TYPE                |         8.4     | EXT_SOURCE_3                |        16.7332  |
| EXT_SOURCE_2                     |         5.86667 | EXT_SOURCE_2                |        16.1962  |
| EXT_SOURCE_1                     |         5.76667 | EXT_SOURCE_1                |         5.1853  |
| EXT_SOURCE_3                     |         5.03333 | DAYS_BIRTH                  |         3.30397 |
| AMT_ANNUITY                      |         2.7     | AMT_GOODS_PRICE             |         2.3219  |
| INS_AMT_PAYMENT_min              |         2.26667 | AMT_ANNUITY                 |         2.31484 |
| BU_DAYS_CREDIT_max               |         2.2     | CODE_GENDER                 |         2.20976 |
| AMT_CREDIT                       |         2.06667 | AMT_CREDIT                  |         1.96831 |
| INS_AMT_PAYMENT_sum              |         1.83333 | NAME_EDUCATION_TYPE         |         1.89402 |
| DAYS_BIRTH                       |         1.66667 | DAYS_EMPLOYED               |         1.7613  |
| AMT_GOODS_PRICE                  |         1.5     | INS_AMT_PAYMENT_min         |         1.56212 |
| OWN_CAR_AGE                      |         1.5     | OCCUPATION_TYPE             |         1.32941 |
| INS_DAYS_ENTRY_PAYMENT_std       |         1.43333 | BU_AMT_CREDIT_SUM_DEBT_mean |         1.26663 |
| POS_SK_DPD_DEF_mean              |         1.26667 | BU_DAYS_CREDIT_max          |         1.15124 |
| CC_CNT_DRAWINGS_ATM_CURRENT_mean |         1.26667 | INS_AMT_PAYMENT_sum         |         1.0503  |

 両モデルが共通してTOP15に挙げた項目: 10件
['AMT_ANNUITY', 'AMT_CREDIT', 'AMT_GOODS_PRICE', 'BU_DAYS_CREDIT_max', 'DAYS_BIRTH', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'INS_AMT_PAYMENT_min', 'INS_AMT_PAYMENT_sum']
'''

#3-1 試走結果に基づくEDA(第1有力指標)　欠損及び基本統計量
'''
第1有力指標 (5%以上)
共通： EXT_SOURCE_1～3 (外部機関によるスコア)
LGBM： ORGANIZATION_TYPE (勤務先の業種)
'''
core_cols1 = ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']

# 統計量と欠損率
def get_stats_summary(df, cols):
    """
    指定したカラムの欠損率と基本統計量をDataFrameで返す
    """
    summary = pd.DataFrame({
        'Missing%': df[cols].isnull().mean() * 100,
        'Mean': df[cols].mean(numeric_only=True),
        'Median': df[cols].median(numeric_only=True),
        'Min': df[cols].min(numeric_only=True),
        'Max': df[cols].max(numeric_only=True)
    })
    return summary

core_summary = get_stats_summary(train, core_cols1)
print(core_summary)

#3-2　試走結果に基づくEDA(第1有力指標)　ヒストグラム(欠損は-0.1として表示)

# 可視化用データの準備
plot_df = train[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'TARGET']].copy()
plot_df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']] = plot_df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].fillna(-0.1)

fig, axes = plt.subplots(3, 1, figsize=(7, 10))
cols = ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']
colors = {0: 'skyblue', 1: 'orange'}

for i, col in enumerate(cols):
    sns.histplot(data=plot_df, x=col, hue='TARGET', bins=100, ax=axes[i],
                 palette=colors, element='step', common_norm=False)

    # 軸をログスケールに変更
    axes[i].set_yscale('log')

    axes[i].xaxis.set_major_locator(ticker.MultipleLocator(0.05))
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].set_title(f'Distribution of {col} (Missing = -0.1)')
    axes[i].axvline(0, color='black', linestyle='--', alpha=0.3)
    axes[i].set_xlabel('Score')
    axes[i].set_ylabel('Count (Log Scale)')

plt.tight_layout()
plt.show()

"""共通して、スコアが高くなるほどデフォルト件数と非デフォルト件数の差の開きが大きくなり、信用度の高い指標であることを確認。  
*   EXT_SOURCE_1  
スコアがあがるほどデフォルト件数は僅かに逓減傾向であり、0.88あたりから急激に下がる。また、欠損の場合はデフォルト率が高い。
*   EXT_SOURCE_2  
スコア0.45あたりまではデフォルト件数は横ばいであり、以降は逓増し、0.65あたりから下がり始め、0.82あたりで0付近となる。また、欠損していてもあまりデフォルト率は高くない。  
*   EXT_SOURCE_3  
スコア0.7あたりまではほぼ横ばいであり、以降は下がり始める。また、欠損の場合のデフォルト率は高い。


"""

#3-3　EXT_SOURCE_1〜3 × TARGET ヒストグラム(密度表示)+point-biserial相関

from scipy import stats

target_df = train

ext_sources = ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']

plt.figure(figsize=(15, 5))

for i, col in enumerate(ext_sources):
    # 2. 欠損値を除外したマスクを作成
    mask = target_df[col].notnull()

    # 3. 点二系列相関の計算
    corr, p_value = stats.pointbiserialr(target_df.loc[mask, 'TARGET'], target_df.loc[mask, col])

    # 4. 可視化
    plt.subplot(1, 3, i+1)
    sns.kdeplot(target_df[target_df['TARGET'] == 0][col], label='TARGET: 0', shade=True, color='royalblue')
    sns.kdeplot(target_df[target_df['TARGET'] == 1][col], label='TARGET: 1', shade=True, color='crimson')

    plt.title(f'{col}\nCorr: {corr:.4f}', fontsize=12)
    plt.xlabel('Score')
    plt.ylabel('Density')
    plt.legend()

plt.tight_layout()
plt.show()

"""密度で見たとき、いずれもスコア0.4～0.5の範囲でデフォルトと非デフォルトの密度の大小の強さが入れ替わっており、スコアが低いほどデフォルトの件数密度が高い傾向にある。  
また形状としてはEXT_SOURCE_1はデフォルトが左寄りで、非デフォルトが山なりの正規分布に近い形状となった。EXT_SOURCE_2はどちらも右寄りである。  
EXT_SOURCE_3はデフォルトがやや左寄りの山なりであり、非デフォルトが右寄りとなった。また、デフォルトのグラフが重なっていない部分の面積が大きく、相関値でも-0.1789と一番傾向がでている。これはCATBOOST試走結果でインポータンス1位となった点と一致する。
"""

#3-4　EXT_SOURCE_1〜3 × TARGET ヒストグラム(密度表示)の境界値

from sklearn.neighbors import KernelDensity

def find_intersection(data, col):
    # 欠損を除外
    mask = data[col].notnull()
    s0 = data.loc[mask & (data['TARGET'] == 0), col].values
    s1 = data.loc[mask & (data['TARGET'] == 1), col].values

    # 各グループの密度推定（KDE）を計算
    # スパン（x軸）を0から1まで1000分割
    x_range = np.linspace(0, 1, 1000).reshape(-1, 1)

    # TARGET=0の密度
    kde0 = KernelDensity(bandwidth=0.03).fit(s0.reshape(-1, 1))
    log_dens0 = kde0.score_samples(x_range)

    # TARGET=1の密度
    kde1 = KernelDensity(bandwidth=0.03).fit(s1.reshape(-1, 1))
    log_dens1 = kde1.score_samples(x_range)

    # 密度が逆転するインデックスを探す
    diff = np.exp(log_dens0) - np.exp(log_dens1)
    idx = np.argwhere(np.diff(np.sign(diff))).flatten()

    if len(idx) > 0:
        return x_range[idx[-1]][0] # 最も右側（高スコア側）の交点を返す
    return None

# 実行と表示
print("--- EXT_SOURCE Border Lines ---")
for col in ['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']:
    border = find_intersection(train, col)
    print(f"{col}: {border:.4f}")

"""FE追加事項

*   平均  
EXT_SOURCE_1～3の平均
*   平均(分母補正あり)  
分子式　EXT_SOURCE_1～3の合計  
分母式　2＋(EXT_SOURCE_2(欠損の場合は0))  
補足：EXT_SOURCE_1、3については欠損時のデフォルト率が高いため、欠損時でも母数に含める  
*   スコアごとのデフォルト率  
スコアを0～1まで0.05刻みでデフォルト率を計算し、各スコアに紐づけ  
補足：グラフ上のデフォルトと非デフォルトのグラフの開差をモデルに認識させるため  
※リーク対策：Out-of-Fold＋Smoothing  
*   幾何平均  
EXT_SOURCE_1～3の乗算の3乗根  
※欠損時は各EXT_SOURCEごとにデフォルト率が近いスコアを適用  
補足：各EXT_SOURCE間にばらつきがある場合の特徴を捉えるため追加  
*   境界値フラグ(EXT_SOURCE_1～3)  
※境界値未満を'1'、境界値以上を'0'  
また、ターゲット値そのものを使うわけではないので、OOF＋Smoothingは実施しない。
--- EXT_SOURCE Border Lines ---  
EXT_SOURCE_1: 0.4284  
EXT_SOURCE_2: 0.4895  
EXT_SOURCE_3: 0.4484  


"""

#3-4　試走結果に基づくEDA(第1有力指標)　ORGANIZATION_TYPE

# 1. 業種ごとのターゲット平均（デフォルト率）を計算
org_target_mean = train.groupby('ORGANIZATION_TYPE')['TARGET'].mean().sort_values(ascending=False)

# 2. 可視化
plt.figure(figsize=(10, 18)) # 種類が多いので縦に長く
sns.barplot(x=org_target_mean.values, y=org_target_mean.index, color='steelblue', edgecolor='black')

# 全体の平均デフォルト率を赤い破線で引く（比較用）
overall_mean = train['TARGET'].mean()
plt.axvline(overall_mean, color='red', linestyle='--', label=f'Overall Average ({overall_mean:.2%})')

plt.title('Default Rate by Organization Type')
plt.xlabel('Default Rate (TARGET Mean)')
plt.legend()
plt.show()

#3-5　試走結果に基づくEDA(第1有力指標)　ORGANIZATION_TYPE カイ二乗検定

from scipy import stats

# 1. 業種(ORGANIZATION_TYPE)とターゲット(TARGET)のクロス集計表を作成
# 行：業種、列：0(完済) or 1(デフォルト)
contingency_table = pd.crosstab(train['ORGANIZATION_TYPE'], train['TARGET'])

# 2. カイ二乗検定を実行
# chi2: 検定統計量, p: p値, dof: 自由度, expected: 期待度数
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)

print(f"--- ORGANIZATION_TYPE Chi-square Test ---")
print(f"Chi-square Statistic: {chi2:.4f}")
print(f"P-value: {p:.4e}") # 非常に小さい値になるため科学的表記

# 3. 業種別のデフォルト率を算出して、上位を確認
org_stats = train.groupby('ORGANIZATION_TYPE')['TARGET'].agg(['mean', 'count'])
org_stats.columns = ['Default_Rate', 'Count']
org_stats = org_stats.sort_values(by='Default_Rate', ascending=False)

print("\n--- Default Rate by Organization (Top 5) ---")
print(org_stats.head())

"""P値が限りなく小さく、有意な差であることを確認

FE追加事項  
*   業種別のデフォルト率  
※リーク対策：Out-of-Fold＋Smoothing  
※組み合わせ特徴量は以降のEDA時に有効なものがあれば追加。

＃3でモデル試走結果が統計的に有意であったことから、第2有力指標以降は試走での寄与度を信頼し、検定は省略
"""

#4-1　試走結果に基づくEDA(第2有力指標)　欠損及び基本統計量
'''
第2有力指標 (2～5%)
共通： AMT_ANNUITY (ローンの年間支払い額)
LGBM： INS_AMT_PAYMENT_min(過去ローンの最小支払額),
　　　 BU_DAYS_CREDIT_max(他社ローンの直近の申請日),
　　　 AMT_CREDIT(融資額)
CAT： DAYS_BIRTH (年齢),
　　　AMT_GOODS_PRICE(商品価格),
　　  CODE_GENDER(性別)
'''
core_cols2 = [
    'AMT_ANNUITY',
    'INS_AMT_PAYMENT_min',
    'BU_DAYS_CREDIT_max',
    'AMT_CREDIT',
    'DAYS_BIRTH',
    'AMT_GOODS_PRICE',
]

core_summary = get_stats_summary(train, core_cols2)
print(core_summary)

#4-2　試走結果に基づくEDA(第2有力指標)　ヒストグラム
# 欠損値を埋めた値を管理
fill_values = {
    'BU_DAYS_CREDIT_max': 300,
    'INS_AMT_PAYMENT_min': -200000
}

# 最新の欠損値処理
df_plot = train.copy()
df_plot['BU_DAYS_CREDIT_max'] = df_plot['BU_DAYS_CREDIT_max'].fillna(300)
df_plot['INS_AMT_PAYMENT_min'] = df_plot['INS_AMT_PAYMENT_min'].fillna(-200000)

# 性別除外リスト
num_cols = [c for c in core_cols2 if c != 'CODE_GENDER']

fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(10, 12))
axes = axes.flatten()

sns.set_style("ticks") # 目盛りを表示するスタイルに固定

for i, col in enumerate(num_cols):
    # --- 描画 ---
    sns.histplot(
        data=df_plot, x=col, hue='TARGET', bins=50,
        multiple='layer', ax=axes[i],
        palette={0: 'steelblue', 1: 'orange'},
        edgecolor='black', alpha=0.6
    )

    # --- 軸の視認性強化（微調整版） ---
    # 1. x軸：下方向にしっかり突き出させる
    axes[i].tick_params(axis='x', which='major', direction='out',
                        length=10, width=2, colors='black', bottom=True)

    # 2. y軸：突き出しをなくす（長さを0にする）
    axes[i].tick_params(axis='y', which='both', length=0)

    # 3. グリッド設定
    axes[i].set_axisbelow(True)
    axes[i].grid(False)
    axes[i].grid(True, axis='x', which='major', ls='--', alpha=0.6, color='gray')
    axes[i].grid(True, axis='y', which='both', ls='-', alpha=0.2, color='silver')

    # --- スケールとタイトルのセット ---
    axes[i].set_yscale('log')

    title_text = col
    if col in fill_values:
        title_text += f' (Missing = {fill_values[col]})'
    axes[i].set_title(title_text, fontsize=12)

plt.tight_layout()
plt.show()

"""*   AMT_ANNUITY (ローンの年間支払い額)  
25000あたりでピークとなり、以降は減少傾向。150000以降はほぼデフォルトなし。額が大きくなるほどデフォルト率は低下。  
*   INS_AMT_PAYMENT_min(過去ローンの最小支払額)  
額が大きくなるほどデフォルト率が減少傾向。欠損時のデフォルト率は高い。  
*   BU_DAYS_CREDIT_max(他社ローンの直近の申請日)  
-2200日付近まではデフォルト率が減少傾向。以降はやや増加。欠損時のデフォルト率は高い。  
*   AMT_CREDIT(融資額)  
金額が大きくなるほどデフォルト率減少傾向。減少傾向の中で一定間隔で件数が増える傾向になるが、増加した前後の棒グラフと比較して明確なデフォルト率の差は見られない。  
*   DAYS_BIRTH (年齢)  
-10000(27歳)まではデフォルト率増加し、以降は逓減傾向。-23750(65歳)から大きく減少。  
*   AMT_GOODS_PRICE(商品価格)  
金額増加に伴ってデフォルト率減少傾向。また、一定間隔で件数が増え、融資額より強くその傾向が表れている。その場合のデフォルト率は前後の棒グラフと比べて、高い場合もあればあまり変わらないように見える場合もある。  

"""

#4-3　試走結果に基づくEDA(第2有力指標)　カテゴリ型の基本情報

col = 'CODE_GENDER'

# 件数とデフォルト率の計算
res = train.groupby(col)['TARGET'].agg(['count', 'mean'])

# カラム名の整理
res.columns = ['件数', 'デフォルト率(%)']
res['構成比(%)'] = (res['件数'] / res['件数'].sum()) * 100
res['デフォルト率(%)'] = res['デフォルト率(%)'] * 100

# 表示用に並べ替え
res = res[['件数', '構成比(%)', 'デフォルト率(%)']].sort_values('デフォルト率(%)', ascending=False)

print(f"▼ カラム名: {col}")
print("-" * 50)
print(res)
print("-" * 50)

"""構成比は女性がおよそ3分の2を占めるものの、デフォルト率は男性の方が3%ほど高く、10.14%となった。

FE追加事項
*   ビン(50)別デフォルト率  
※リーク対策：Out-of-Fold＋Smoothing  
*   キリ番(AMT_CREDIT,AMT_GOODS_PRICE)  
一定間隔で件数が増えることから、le4,le5,le6別で除算した数に小数点以下を含まないものについてフラグを追加  
  

組み合わせについては以降のEDAで検討。
"""